- app/config.py
- app/templates/secure-messages-draft.html
Below Issues fixed:
- Characters after space in subject field is persisted but not displayed
- Remove bullet point displayed after saving draft
- Make link work after saving draft
> Updated save message as draft feature

- Procfile
> Fix Procfile to run app in Cloud Foundry.

- .gitignore
- app/application.py
- app/templates/error.html
- app/templates/partials/header.html
- app/views/surveys.py
- requirements.txt
- scripts/run.sh
- Removed all code related to session management.
- Inserted jwt_session wrapper for all calls where which require an authenticated session
- Session wrapper will redirect to not-logged-in if there is no current (JWT) session
- Login/Logout now manage a cookie rather than storing the JWT in a session
> Removed session handling and replaced with JWT session handler

- app/templates/secure-messages-create.html
- app/templates/secure-messages-draft.html
- app/templates/secure-messages-view.html
- app/views/secure_messaging.py
- app/views/surveys.py
- tests/selenium_scripts/test_draft.py
- tests/selenium_scripts/test_modify_status.py
- tests/selenium_scripts/test_send_message.py
- [Trello card](https://trello.com/c/d6gHlGxG)
- Adding save draft functionality to draft page
- Check all functionality works correct
- Some duplicate code(maybe suggest way to cut code down/re-use)
> Sm067 save draft reply

- app/views/secure_messaging.py
> fixed flake8 issues

- app/templates/error.html
- app/templates/layouts/_base.html
- app/templates/layouts/_onecol.html
- app/templates/layouts/_twocol.html
- app/templates/login.html
- app/templates/partials/question.html
- app/templates/passwords/forgot-password.html
- app/templates/passwords/reset-password.html
- app/templates/register/register.activate-account.html
- app/templates/register/register.enter-your-details.html
- app/templates/register/register.help-with-email.html
- app/templates/register/register.link-expired.html
- app/templates/secure-messages-create.html
- app/templates/secure-messages-draft.html
- app/templates/secure-messages-view.html
- app/templates/secure-messages.html
- app/templates/sign-in/sign-in.html
- app/templates/sign-in/sign-in.last-attempt.html
- app/templates/surveys/surveys-access.html
- app/templates/surveys/surveys-upload-file-picker.html
- tests/test_surveys.py
**What is the context of this PR**
Trello card - [https://trello.com/c/aox0ZwCQ](https://trello.com/c/aox0ZwCQ)
This PR adds id's to elements to make testing easier
**How to review**
Review files and check id's exist and point out any missing id's
> Added id's to HTML elements

- app/templates/secure-messages-draft.html
- app/templates/secure-messages.html
Changed the font for the draft saved message to the correct font.
> D 143 incorrect draft font

- app/views/surveys.py
Improve logging for survey download.
> Improve survey download logging.

- frontstage/views/secure_messaging.py
Add errors blueprint for url lookups.
> Error blueprint url updates.

- frontstage/templates/register/register.confirm-organisation-survey.html
These are changes from pull request https://github.com/ONSdigital/ras-frontstage/pull/83 by @saedwards which have been made compatible with the recent merges.
> moving pull request changes to updated branch

- frontstage/views/secure_messaging.py
- frontstage/views/sign_in.py
Replaced user_uuid with party_id and tested locally
> Replaced use of user_uuid with party_id

- frontstage/views/secure_messaging.py
- frontstage/views/sign_in.py
[Trello Card](https://trello.com/c/zKGpcaUs)
removed hardcoding for collection case in create message
> Ts 221 modify secure message collection case hardcoded

- frontstage/views/secure_messaging.py
Draft can now be modified then sent, and the draft being deleted on send.
> D 149 bug save draft

- frontstage/templates/secure-messages-create.html
- frontstage/templates/secure-messages-draft.html
Removed the required tags in html
> D-151-unable-to-save-draft-without-text-in-body

- frontstage/templates/surveys/surveys-download-failure.html
- frontstage/views/surveys.py
Merged new template from old feature branch feature/us155-respondent-fails-to-download-a-bres-survey-3-s
Branch was too old to merge because of project refactoring.
> Add download error page.

- frontstage/views/register.py
Small change to return a 202 status code on a failed iac code request
> adding 202 response for failed iac call

- frontstage/views/__init__.py
- frontstage/views/info.py
- Added an endpoint to view info for the page.
- Hardcoded at the moment.
- Url -> '/info'
> added info endpoint

- frontstage/views/register.py
- tests/test_account_activation.py
Made small variable name changes to register and tests to integrate with party service registration.
> making variable name changes asked for by mark

- frontstage/templates/surveys/surveys-download-failure.html
- Removed back button from download-survey-error page.
> removed back button

- frontstage/views/register.py
- frontstage/views/sign_in.py
> removing commented code from sign in and register

- config.py
- frontstage/error_handlers.py
- frontstage/views/secure_messaging.py
removed log line which was causing issues, also removed an unnecessary session call in frontstage
> Connection error error handler should only pick up requests module errors

- frontstage/views/secure_messaging.py
- tests/test_data/example_message.json
- tests/test_secure-message.py
Added missing tests and fixed a couple of small errors brought up by the testing
> Ts208 improve unit test coverage secure messaging

- frontstage/templates/secure-messages/secure-messages-draft.html
- frontstage/templates/secure-messages/secure-messages-sent-view.html
Cancel button was redirecting to message inbox from draft and sent views.
> resolving redirect issue

- frontstage/views/register.py
- tests/test_account_activation.py
https://trello.com/c/sSMpZqHh/488-email-verification-handle-expired-token-correctly-13
Handling response of email verification call using status codes rather than content of response
Improved error handling
Improved tests
> updating handling of email verification response+tests

- frontstage/templates/sign-in/sign-in.html
adding / so link doesn't redirect to http
> adding / to create account link

- frontstage/templates/register/register.enter-your-details.html
- tests/test_registration.py
small change linked to card https://trello.com/c/YZe4W5Wd/580-defect-15-story-us001-release-10-validation-error-message-not-as-expected
> repalcing _ values with spaces

- frontstage/logger_config.py
Added file name and line number to logger_config
> adding file name and line number to logger

- frontstage/views/secure_messaging.py
added app.config[] to secure_messaging.py to fix builtins.error
> fix error in sent tab

- frontstage/views/surveys.py
- tests/test_data/case_categories.json
- tests/test_surveys.py
Redid the tests for the surveys.py file
> improved tests for surveys blueprint

- frontstage/views/surveys.py
Removing comments and unused code in the build_survey_data function.
Also improved error handling and logging
> tidying build survey data code

- tests/test_app.py
- tests/test_sign_in.py
Created a new `test_sign_in.py` file to test sign-in blueprint and cleaned up the `test_app.py` file
> Tested sign-in blueprint more thoroughly

- frontstage/views/register.py
- tests/test_data/case_categories.json
- tests/test_registration.py
Adding more testing to `test_registration.py` and formatting other tests more similarly to other files
> improving test_registration

- tests/test_registration.py
One test is commented out as it relates to another pull request 
https://github.com/ONSdigital/ras-frontstage/pull/148
> adding tests for enter details enrolment form

- frontstage/views/sign_in.py
- tests/test_sign_in.py
Had to make a few small changes for issues in surveys.py which were noticed when making the tests
> adding tests for oauth sign in errors

- frontstage/templates/surveys/surveys.html
- frontstage/views/surveys.py
`surveys.html` now checks for a `history` variable which if `True` removes the submit-by field
> Defect 16 - 'Submit by' column must not be present on History page

- frontstage/templates/secure-messages/message-error-summary.html
- frontstage/templates/secure-messages/secure-messages-create.html
Test with corresponding secure message PR
https://github.com/ONSdigital/ras-secure-message/pull/91
> updated parsing of form errors

- config.py
- frontstage/common/post_event.py
- frontstage/views/register.py
- frontstage/views/secure_messaging.py
- frontstage/views/sign_in.py
- frontstage/views/surveys.py
Added basic authentication configuration and added this to the requests made from frontstage
> adding basic authentication to requests made from frontstage

- frontstage/views/secure_messaging.py
I broke frontstage, this removes the basic-auth to secure messaging to fix it
> removing basic-auth from sm blueprint

- frontstage/__init__.py
- frontstage/error_handlers.py
- frontstage/logger_config.py
- frontstage/models.py
- tests/behavioural/features/steps/common.py
- tests/behavioural/features/steps/test_history_tab.py
- tests/behavioural/features/steps/test_send_message.py
- Minor fixes for pylint/flake
> fixed a couple of pylint/flake issues

- frontstage/__init__.py
Added the header `{ "X-Frame-Options": "DENY" }` to all incoming requests
linked to card https://trello.com/c/OB1d5agL/597-defect-28-cross-site-framing-vulnerability
> Defect-28 adding framing header

- config.py
- frontstage/jwt.py
Will have to confirm how these will be set in the deployed environments
https://trello.com/c/Xx7kjy4m/553-read-jwt-secret-and-algorithm-from-environment
> setting JWT config with environment variables

- frontstage/templates/secure-messages/secure-messages-draft.html
Edited secure-messages-draft template to handle the subject field correctly
> fixing handling of subject in draft view

- frontstage/logger_config.py
Removing file name and line number from logger so splunk can parse the json format
> removing file name and line number from logger

- config.py
- frontstage/templates/passwords/forgot-password.html
- frontstage/templates/passwords/reset-password.html
- frontstage/templates/register/register.activate-account.html
- frontstage/templates/register/register.confirm-organisation-survey.html
- frontstage/templates/register/register.enter-enrolment-code.html
- frontstage/templates/register/register.enter-your-details.html
- frontstage/templates/sign-in/sign-in.html
- frontstage/templates/sign-in/sign-in.last-attempt.html
- frontstage/templates/surveys/surveys-upload-file-picker.html
- frontstage/templates/surveys/surveys.html
Adding token to all forms.
Probably check to see that none have been missed before merging
> adding csrf_token to forms

- gunicorn.py
Using a standard gunicorn settings file.
> Update gunicorn settings.

- frontstage/templates/errors/404-error.html
- frontstage/templates/errors/500-error.html
- frontstage/templates/errors/error.html
- frontstage/templates/errors/not-signed-in.html
- tests/app/test_secure-message.py
- Removed mention of 'protected endpoints'
- Replaced "log in" and "login" with "Sign in" etc.
- Changed the page title tags to be consistent with our other pages.
> Updated content in error pages

- frontstage/templates/cookies-privacy.html
- frontstage/templates/login.html
- frontstage/templates/passwords/forgot-password.check-email.html
- frontstage/templates/passwords/forgot-password.html
- frontstage/templates/passwords/reset-password.confirmation.html
- frontstage/templates/passwords/reset-password.html
- frontstage/templates/register/register.activate-account.html
- frontstage/templates/register/register.almost-done.html
- frontstage/templates/register/register.confirm-organisation-survey.html
- frontstage/templates/register/register.email-resent.html
- frontstage/templates/register/register.enter-enrolment-code.html
- frontstage/templates/register/register.enter-your-details.html
- frontstage/templates/register/register.link-expired.html
- frontstage/templates/secure-messages/message-success-temp.html
- frontstage/templates/secure-messages/secure-messages-create.html
- frontstage/templates/secure-messages/secure-messages-draft.html
- frontstage/templates/secure-messages/secure-messages-sent-view.html
- frontstage/templates/secure-messages/secure-messages-view.html
- frontstage/templates/sign-in/sign-in.account-not-verified.html
- frontstage/templates/sign-in/sign-in.locked-account.html
- frontstage/templates/sign-in/sign-in.trouble.html
- frontstage/templates/surveys/surveys-access.html
- frontstage/templates/surveys/surveys-download-failure.html
- frontstage/templates/surveys/surveys-upload-failure.html
- frontstage/templates/surveys/surveys-upload-success.html
- gunicorn.py
- tests/app/test_account_activation.py
- tests/app/test_secure-message.py
Brought all the page <title> tags in line with what we'd specified in confluence
> Update page title tags

- config.py
- frontstage/__init__.py
- frontstage/common/authorisation.py
- frontstage/exceptions/exceptions.py
- Removed default value for JWT_ALGORITHM
- Removed leftover jwt-secret/algorithm from authorisation file
- Added Exception to fail application when a non-defaulted environment variable is not defined
> Defect-25 Information Disclosed via GitHub Continued

- frontstage/views/register.py
- Lower the case of the enrolment code at the point of entry into the code
> lowering the case of enrolment code when entered

- frontstage/templates/sign-in/sign-in.locked-account.html
- frontstage/templates/sign-in/sign-in.trouble.html
Removed mention of locked/disabled account, including in the page <title>
> Removing mention of locked/disabled account

- frontstage/jwt.py
Removed scope and email address from JWT
> removing scope and email from jwt

- frontstage/templates/surveys/surveys-upload-failure.html
- tests/app/test_surveys.py
Added if statement to html to accommodate Upload CI error messages
> adding if for seperate error messages

- config.py
- frontstage/models.py
- frontstage/templates/passwords/forgot-password.check-email.html
- frontstage/templates/passwords/password-expired.html
- frontstage/templates/passwords/reset-password.html
- frontstage/views/passwords.py
- tests/app/test_passwords.py
- Updated password blueprint templates to match story
- Added password reset link expired template `passwords/link-expired.html`
- Added code to passwords blueprint to make and process required calls to party service
- Should be fully tested
https://trello.com/c/02XvOKBs/488-us012-reset-forgotten-password-8sp
For functionality to work will require the party service endpoints to be available
> Feature/us012  reset forgotten password

- frontstage/views/surveys.py
Going through splunk to track issue behind failed uploads showed logs did not have enough information.
> add upload error info in log

- frontstage/templates/contact-us.html
Contact us page: made telephone number a hyperlink using international version of number
> Contact us page: made telephone number a hyperlink

- frontstage/templates/layouts/_base.html
- frontstage/templates/partials/header.html
Following google's recommendation.
> Removed ga code from <header> and put in <head>

- config.py
- frontstage/common/api_call.py
- frontstage/jwt.py
- frontstage/views/secure_messaging.py
- frontstage/views/sign_in.py
- tests/app/test_secure_message.py
- tests/app/test_sign_in.py
This PR works in conjunction with this frontstage-api PR https://github.com/ONSdigital/ras-frontstage-api/pull/8
- Moved sign in calls to single frontstage-api call which returns oauth2 token details and party_id
- Updated testing
> TBL087/Moving Sign-In calls to Frontstage-Api

- frontstage/views/contact_us.py
- frontstage/views/cookies_privacy.py
- tests/app/test_cookies_and_contact.py
Added a couple of tests to cover the `/cookies-privacy` and `/contact-us` endpoints
> Add tests for untested endpoints

- frontstage/models.py
- frontstage/templates/secure-messages/message-form.html
- frontstage/views/secure_messaging.py
- package-lock.json
- package.json
- tests/app/test_secure_message.py
Aligned the secure message form template with the rest of frontstage, using FlaskForm's.
Several hidden fields have to be passed through when loading this form to initialise it with the right data for both a draft and a viewed thread message.
> Use FlaskForm forms for secure messaging view

- frontstage/__init__.py
- frontstage/common/api_call.py
- frontstage/views/contact_us.py
- frontstage/views/cookies_privacy.py
- frontstage/views/errors.py
- frontstage/views/info.py
- frontstage/views/passwords.py
- frontstage/views/register.py
- frontstage/views/secure_messaging.py
- frontstage/views/sign_in.py
- frontstage/views/surveys.py
Improved the general logging quality throughout
Also fixed several linting errors, mostly around line length
[trello](https://trello.com/c/soVzqN6L/4-bring-logging-standards-in-line-with-sdc-logging-standards)
> Update logging to match SDC standards

- Dockerfile
- config.py
- run.py
Align default port numbers for all apps and default basic auth. Port numbers for all apps can be found here: https://digitaleq.atlassian.net/wiki/spaces/RASB/pages/94863418/Developer+Environment+Port+Mappings
> align ports and basic auth

- frontstage/cloud/cloudfoundry.py
Tagged as release_13 and deployed successfully to SIT and PREPROD
> Change the get_service to name rather then label

- frontstage/templates/passwords/reset-password.html
- frontstage/templates/sign-in/sign-in.html
- frontstage/templates/sign-in/sign-in.last-attempt.html
Remove the toggle button for frontstage
> Remove show password toggle

- config.py
- tests/app/test_jwt_authorization.py
- tests/app/test_secure_message.py
- tests/app/test_surveys.py
> Update default secret key

- tests/app/test_jwt_authorization.py
- tests/app/test_secure_message.py
- tests/app/test_surveys.py
Previously the test jwt's expired after an hour.
These have been updated with one which will last a lot longer
> Update test JWTs to not expire

- README.md
- config.py
- frontstage/views/info.py
- Removed the more detailed information about pyenv and pipenv in favour of just providing links for how to use these
- Removed the frontend js setup, no ones been using this and I think it should be removed
- Updated the configuration table
- Added Redis installation instructions
- Removed some unnecessary config from config.py, we shouldnt need to set the version/name with environment variables
> Update README.md and clean up config.py

- frontstage/logger_config.py
Use stdout for application logging instead of default stderr.
> Update logging to use stdout

- config.py
- frontstage/templates/surveys/surveys.html
- frontstage/views/surveys/access_survey.py
- tests/app/test_surveys.py
Required for US062: EXT - Access an eQ, this is the frontend. Do not merge until https://github.com/ONSdigital/ras-frontstage-api/pull/39 has been merged
> Us062 access eq

- frontstage/templates/surveys/surveys.html
Required for: https://github.com/ONSdigital/rasrm-acceptance-tests/pull/61
> Add ids for tests

- frontstage/templates/surveys/surveys.html
Add ID with counter for acceptance test 
[Trello](https://trello.com/c/q5skwt1o/91-us050a-int-manually-change-the-response-status-for-a-given-ru-survey-ce-to-completed-by-phone-xl)
> Us050 change response status

- frontstage/templates/surveys/surveys.html
This PR fixes the defect where the period shown to the respondent wasn't wrapped correctly - https://trello.com/c/sLSYLjUy
> Fix wrapping text defect

- frontstage/templates/surveys/surveys-upload-file-picker.html
- frontstage/templates/surveys/surveys-upload-success.html
- frontstage/views/surveys/upload_survey.py
- tests/app/test_surveys.py
Pass survey name to upload successful template and add it to template
> Use correct survey name for upload complete message

- frontstage/templates/surveys/surveys-upload-file-picker.html
- frontstage/templates/surveys/surveys-upload-success.html
- frontstage/views/surveys/upload_survey.py
Replace survey name with generic 'This' in upload successful template
> Use generic upload successful message

- frontstage/templates/surveys/surveys.html
This one character white space nearly broken Vibhor when performance testing.
> Remove white space in URL

- frontstage/templates/partials/tab_list.html
- frontstage/templates/secure-messages/messages.html
- frontstage/templates/surveys/surveys-history.html
- frontstage/templates/surveys/surveys-todo.html
- frontstage/views/surveys/surveys_list.py
- tests/app/test_sign_in.py
- tests/app/test_surveys.py
The same code was being used in multiple files, so created a partial to re-use
> Moved duplicate code into single partial

- frontstage/templates/surveys/surveys.html
- tests/app/test_surveys.py
- tests/test_data/surveys_list_no_trading_as.json
Displaying trading as only if there is a value.
> Us110 display trading as

- config.py
- frontstage/controllers/conversation_controller.py
- frontstage/create_app.py
- frontstage/views/secure_messaging/create_message.py
- tests/app/test_secure_message.py
Removed usage of frontstage-api calls to secure-message and call directly
> Refactor to send directly to secure message api

- frontstage/templates/surveys/surveys.html
Added a few new html names etc to help with the acceptance tests
> Update html tags for acceptance tests

- frontstage/templates/surveys/surveys-todo.html
- frontstage/templates/surveys/surveys.html
> Fixes hardcoded new survey link in list

- frontstage/templates/cookies-privacy.html
The tables in the page should now display visually correctly
> Corrected the class names in the tables

- config.py
Upping version to 0.4.6 for performance 650 release
> Preparing releas_perf_650

- frontstage/common/message_helper.py
- frontstage/controllers/conversation_controller.py
- frontstage/error_handlers.py
- frontstage/logger_config.py
- frontstage/views/secure_messaging/message_get.py
- tests/app/test_logger_config.py
Currently in Splunk the errors are displaying 'incorrectly' now with the updated logging, it should appear much more readable in Splunk.
Card: https://trello.com/c/CYTY3NKF/229-log-exception-traces-as-json-in-frontstage-s
- Check when you get an exception if it outputs correctly in the log as a single JSON block.
- Run tests the usual.
> Log Exception traces as JSON in Frontstage

- frontstage/controllers/iac_controller.py
- frontstage/views/passwords/forgot_password.py
A recent change has introduced some invalid use of logging, concerning the log level
log level changed to correctly output log level
Raise logging found:
- In iac_controller.py line 25 and line 32 
- In forgot_password.py line 41 and line 45
fixes #371
> Fix invalid use of logger

- frontstage/templates/partials/business_survey_credentials.html
- frontstage/templates/register/register.almost-done.html
- frontstage/templates/register/register.confirm-organisation-survey.html
Required to complete enrolment acceptance test
Several element IDs added
run as part of full acceptance run
see rasrm-acceptance-tests repo #https://github.com/ONSdigital/rasrm-acceptance-tests/pull/155
N/A
> Changes required for Enrolment acceptance test

- Pipfile
- Pipfile.lock
Upgrade cryptography to address known vulnerability
Run AT against this branch, should still all pass
> Updated sdc-cryptography version to address known vulnerability

- frontstage/templates/login.html
- frontstage/templates/partials/header.html
- frontstage/templates/passwords/forgot-password.html
- frontstage/templates/passwords/reset-password.html
- frontstage/templates/register/register.activate-account.html
- frontstage/templates/register/register.enter-enrolment-code.html
- frontstage/templates/register/register.enter-your-details.html
- frontstage/templates/secure-messages/conversation-view.html
- frontstage/templates/sign-in/sign-in.html
- frontstage/templates/surveys/surveys-access.html
- frontstage/templates/surveys/surveys-add.html
- frontstage/templates/surveys/surveys-confirm-organisation.html
- frontstage/templates/surveys/surveys-todo.html
- frontstage/templates/surveys/surveys-upload-file-picker.html
- frontstage/templates/surveys/surveys.html
Make frontstage button id naming consistent.
changed button ids in rasrm-acceptance-tests & ras-frontstage repos
test locally in PyCharm etc... or from local docker image i.e docker build -t frontstage-ade .
all acceptance tests should pass.
https://github.com/ONSdigital/rasrm-acceptance-tests
> 1st stage of button id naming

- config.py
bump version to 0.5.1 for next release. fyi, it looks like this wasn't merged back for the 0.5.0 release
version number in config.py
> bump version to v0.5.1

- frontstage/templates/surveys/surveys-upload-failure.html
Allows redirect from failed survey upload page to survey todo list.
> Add quotes for tag in url redirect

- frontstage/controllers/iac_controller.py
- frontstage/views/register/create_account.py
- frontstage/views/surveys/add_survey_submit.py
- tests/app/test_registration.py
Stop spamming splunk logs and causing alerts.
Change iac code not active or found is handled.
Trello: https://trello.com/c/DylkAFhC
> Adjust log level for iac not found

- frontstage/controllers/case_controller.py
- frontstage/views/sign_in/sign_in.py
Adds extra context to logs to help with alerting
Trello: https://trello.com/c/bdY6GFqq
> Improve logging for alerts

- .travis.yml
- Makefile
- Pipfile.lock
- tests/app/controllers/test_party_controller.py
- tests/app/views/surveys/test_upload_survey_failed.py
GitHub flagged an insecure version of the Requests package.
- All packages have been updated to their latest versions (where possible).
`make test`
- Screenshot attached
> T008 Update packages to latest version

- frontstage/templates/sign-in/sign-in.account-locked.html
Grammer change
Added a missing 'a' to a sentence.
Enter bad password 10 times and look at the warning text. Should be: 
Check your email
You've tried to sign in a few times with the wrong details.
If example@example.com is registered to an account, we'll send an email explaining how to sign in.
https://trello.com/c/3g2pVBKC
> Update wording in template

- frontstage/common/eq_payload.py
- tests/app/test_generate_eq.py
This just adds a unit test for the work done in https://github.com/ONSdigital/ras-frontstage/pull/422
> Convert UTC unit tests

- config.py
> Update version to 1.12.0

- .gitignore
Simple addition to the gitignore file to not save vscode settings inadvertently.
> Added vscode folder to gitignore file

- config.py
> upgrading version for deployment

- frontstage/error_handlers.py
- tests/app/test_secure_message.py
A recent change that went in had broken a test, this PR fixes it
- Fixed broken Secure Message test
- Run the tests
- Try accessing a message which you don't have access to
> fixed broken Secure Message test

- config.py
> increasing version

- frontstage/controllers/case_controller.py
- frontstage/controllers/collection_exercise_controller.py
- frontstage/controllers/collection_instrument_controller.py
- frontstage/controllers/conversation_controller.py
- frontstage/controllers/iac_controller.py
- frontstage/controllers/oauth_controller.py
- frontstage/controllers/party_controller.py
- frontstage/controllers/survey_controller.py
- frontstage/i18n/translations.py
- frontstage/models.py
- frontstage/views/register/enter_account_details.py
A large part of the logging is at DEBUG level.  The app defaults to INFO, and wasn't being changed in production.
Almost everywhere there was logger.debug it's been changed to logger.info.  For each line I changed, I made sure there was no sensitive information, but make sure to double check case anything was missed!
Unit tests still pass.  Change logging level to info and see the logging appear too?
> Change most logger.debug to logger.info

- frontstage/views/sign_in/sign_in.py
When tidying up the auth code, there was a function that was left over that wasn't deleted. This PR removes it
- Unit tests pass
> Removed unused oauth code

- config.py
Tag version number for release
> updated version number

- config.py
> update to v1.15.1

- config.py
> updating version to 1.16.1

- frontstage/views/secure_messaging/create_message.py
We didn't log out the ru_ref enough in the logging
Where ru_ref available, log it to make debugging easier
> log out ru_ref

- scripts/README.md
- scripts/accounts-to-be-deleted.txt
- scripts/delete_users.sh
We needed a way to delete users, this script gives us a simple way to do so.
Note, this needs to live in frontstage because it's the only place where I've got access to both the auth url and the party url
Added a script that reads a file full of email addresses and deletes them by hitting 2 services.
Add some users to the accounts-to-be-deleted.txt file, set up the enviornment variables that are needed `export SECURITY_USER_NAME=<blah>` for example.
The script should go through and delete all the users.
https://trello.com/c/tLf5PUHz
> Delete users script

- config.py
> upgrading version

- Pipfile.lock
> Fix security issue in ecdsa

- scripts/delete_users.sh
The delete script didn't originally have error handling as it was meant to be a 1 time use thing.  But if an error happens on the first step, it actually messes things up in a difficult to reverse way.  This PR adds checks for expected status codes from each section and stops the process if anything isn't as expected.
> Add error handling to delete script

- Pipfile.lock
Since deploying the latest version of the code onto preprod, we've occasionally gotten RecursionErrors in gunicorn.  Looking at the changelog https://docs.gunicorn.org/en/stable/news.html, in 20.0.1 (this release was on 20.0.0) there was a fix for this.
> Update packages (most noteably gunicorn)

- frontstage/static/js/script.js
- frontstage/templates/layouts/_base.html
- frontstage/templates/login.html
- frontstage/templates/passwords/forgot-password.html
- frontstage/templates/passwords/reset-password.html
- frontstage/templates/register/register.activate-account.html
- frontstage/templates/register/register.enter-enrolment-code.html
- frontstage/templates/register/register.enter-your-details.html
- frontstage/templates/sign-in/sign-in.html
- frontstage/templates/surveys/surveys-add.html
- frontstage/templates/surveys/surveys-confirm-organisation.html
- frontstage/templates/surveys/surveys-upload-file-picker.html
- frontstage/templates/surveys/surveys.html
Issue with forms being submitted multiple times due to multiple button clicks.
Added a script that disables a button for 1 second.
NOTE - this is a temp fix until we refactor to use design system components.
Check all forms submit ok. Test for double submissions.
> Added a temp script to disable button after submit for 1 second

- config.py
> version 1.19.1 release

- config.py
- frontstage/controllers/notify_controller.py
- frontstage/views/passwords/reset_password.py
The code in preprod didn't work because of a missing environment variable.   It also swallowed this logging so it was more difficult to diagnose.
This PR fixes this issue and improves the logging for future times this happens.
> Email logging bugfix

- _infra/helm/Chart.yaml
- _infra/helm/templates/oauth-secret.yaml
- _infra/helm/values.yaml
Remove cpu request and remove the oauth secret.
> remove cpu and secret

- frontstage/common/utilities.py
- frontstage/controllers/oauth_controller.py
- frontstage/controllers/party_controller.py
- frontstage/views/sign_in/sign_in.py
- frontstage/views/surveys/surveys_list.py
- tests/app/test_passwords.py
- tests/app/test_sign_in.py
The metadata and amount of logging isn't great, especially around logging in.  This PR improves that
> Improve metadata on logging

- _infra/helm/templates/deployment.yaml
- _infra/helm/values.yaml
Input the correct ras-partyh env var
> correct the ras poarty env var and remove redundant values

- Makefile
- _infra/docker/Dockerfile
- _infra/helm/templates/deployment.yaml
- _infra/helm/templates/secret.yaml
- _infra/helm/values.yaml
1. Creating a specific Dockerfile for kubernetes which runs gunicorn rather than the development server.
1. Also adding Kubernetes secret for any frontstage specific secrets.
> Kubernetes Image and Secret

- _infra/helm/frontstage/templates/deployment.yaml
> Use container port and quote string values

- _infra/helm/frontstage/templates/deployment.yaml
- _infra/helm/frontstage/values.yaml
> separate database config

- _infra/helm/frontstage/templates/deployment.yaml
- _infra/helm/frontstage/values.yaml
> standardise db config

- _infra/helm/frontstage/templates/deployment.yaml
- _infra/helm/frontstage/values.yaml
> remove database config

- _infra/helm/frontstage/templates/deployment.yaml
- _infra/helm/frontstage/templates/service.yaml
- _infra/helm/frontstage/values.yaml
> add redis templating

- _infra/helm/frontstage/templates/ingress.yaml
> Fix ingress template

- _infra/helm/frontstage/templates/ingress.yaml
> service port is not hardcoded

- _infra/helm/frontstage/templates/backendconfig.yaml
- _infra/helm/frontstage/templates/service.yaml
> add cloud-armor config

- _infra/helm/frontstage/templates/deployment.yaml
- _infra/helm/frontstage/values.yaml
> Add missing config

- _infra/helm/frontstage/templates/deployment.yaml
> add enclosing quotes

- _infra/helm/frontstage/templates/service.yaml
> remove escape char

- _infra/helm/frontstage/templates/deployment.yaml
- _infra/helm/frontstage/values.yaml
Adding SCHEME environment variable to enable switching between http a…nd https
> HTTPS - Adding Scheme env 

- _infra/helm/frontstage/templates/deployment.yaml
- _infra/helm/frontstage/values.yaml
> Add EQ url

- _infra/helm/frontstage/templates/backendconfig.yaml
> add affinityType to session affinity

- _infra/helm/frontstage/templates/backendconfig.yaml
> Affinity type

- _infra/helm/frontstage/templates/secret.yaml
> add unversioned annotation

- _infra/helm/frontstage/Chart.yaml
- _infra/helm/frontstage/templates/deployment.yaml
- _infra/helm/frontstage/values.yaml
Adds kube_dns addresses for all connecting services to allow us to have circular references
> Create DNS entries for each service

- _infra/spinnaker/deployment-full.json
> add misssing vars

- _infra/helm/frontstage/templates/deployment.yaml
> Add missing environment variable

- _infra/helm/frontstage/templates/deployment.yaml
> Add missing email config value

- _infra/helm/frontstage/templates/deployment.yaml
- _infra/helm/frontstage/values.yaml
- config.py
- frontstage/__init__.py
- frontstage/create_app.py
Reordering the CSRF setup and adding a configurable time out for the token
> Fix for the broken CSRF

- config.py
> WTF CSRF limit convert to int

- _infra/helm/frontstage/templates/deployment.yaml
> Fix config error

- _infra/helm/frontstage/templates/deployment.yaml
> Add https to account urls

- _infra/helm/frontstage/templates/deployment.yaml
> Fix logout url

- frontstage/views/sign_in/sign_in.py
> Authorization cookie should be secure and http only

- _infra/helm/frontstage/Chart.yaml
- frontstage/views/sign_in/sign_in.py
- tests/app/test_sign_in.py
Fixes resend verification page - at the moment it is displaying a page not found as the party id is missing from the request url
https://trello.com/c/8YPESOEs/1802-s7-migration-testing-page-not-found-clicking-resend-email-verification
> Fix resend verification email page

- _infra/helm/frontstage/Chart.yaml
> Increment chart version

- _infra/helm/frontstage/templates/ManagedCertificate.yaml
- _infra/helm/frontstage/templates/ingress.yaml
> add logic for pre-shared and managed certitifacte

- frontstage/templates/errors/400-error.html
- frontstage/templates/errors/500-error.html
Amended contact link for 400 errors, per request in Trello card (link below)
400 errors formerly redirected to:
https://www.ons.gov.uk/aboutus/contactus/surveyenquiries
...but now redirect to
https://surveys.ons.gov.uk/contact-us
...by simple change to 400-error.html.
This passes current unit tests and acceptance tests.
To test manually, add an enrolment code in external, confirm, then use the back arrow at top of page, then go forward again. The error message in preprod should link to:
https://surveys.onsdigital.uk/contact-us
https://trello.com/c/txnAYK8g
> Enrolment link

- _infra/helm/frontstage/Chart.yaml
- frontstage/logger_config.py
- tests/app/test_logger_config.py
> Changes to the structlog processor to add severity for the stackdrive

- Pipfile
- Pipfile.lock
> Revert werkzeug change

- .github/workflows/main.yml
- _infra/helm/frontstage/Chart.yaml
> replace concourse

- Makefile
Restored pipenv check that was turned off in previous hotfix for pipenv bugs
- make unit-tests
- make integration-tests
https://trello.com/c/3ZxIpfsX
https://github.com/ONSdigital/ras-frontstage/pull/531
> restored pipenv check to Makefile

- _infra/helm/frontstage/Chart.yaml
- frontstage/routes.md
- frontstage/views/surveys/upload_survey.py
- tests/integration/views/surveys/test_upload_survey.py
> Remove 'upload_survey' endpoint and update tests

- .github/workflows/comment.yml
- .github/workflows/main.yml
- _infra/helm/frontstage/Chart.yaml
> Make dev docker tag changes

- .github/workflows/main.yml
- Dockerfile
- Makefile
- _infra/docker/Dockerfile
- _infra/helm/frontstage/Chart.yaml
- dev-requirements.txt
- requirements.txt
Replaced pipenv in the Dockerfile with a `requirements.txt` generated by `pipenv` in the `Makefile`, to ensure reproducible builds in containers. 
Changed `pipenv install` to `pip install -r requirements` in Dockerfiles and GitHub workflow
Added step to Makefile for pipenv build of requirements.txt from lockfile
- in a dev cluster, spin up the frontstage pod with the image `requirements-txt`
- run acceptance tests
https://trello.com/c/PQZNp4Wo
> Install from requirements.txt in Docker container

- Makefile
- README.md
- _infra/helm/frontstage/Chart.yaml
Update to https://github.com/ONSdigital/ras-frontstage/pull/592, noting that we now use `pip install` to build containers, not pipenv.
> updated README and Makefile

- .github/workflows/comment.yml
- _infra/helm/frontstage/Chart.yaml
Minor version increment for session messaging and overseas users
> incremment minor and fix issue comment user

- _infra/helm/frontstage/Chart.yaml
- frontstage/models.py
Updating logger validation message, following last change to registration form in PR 589
- `make unit-tests`
- `make integration-tests`
- https://github.com/ONSdigital/ras-frontstage/pull/589
- https://trello.com/c/331UX3Uw
> corrected logger msg for phone num validation

- _infra/helm/frontstage/Chart.yaml
- frontstage/controllers/collection_instrument_controller.py
- frontstage/views/surveys/upload_survey.py
- frontstage/views/surveys/upload_survey_failed.py
- tests/integration/views/surveys/test_upload_survey.py
Reverts ONSdigital/ras-frontstage#599
broke collection-instrument
> Revert "adding functionality to reject 0 byte files"

- _infra/helm/frontstage/Chart.yaml
- config.py
- frontstage/templates/secure-messages/conversation-list.html
Styling was missing from the open/closed links on messages.
Should look normal now.
> Fixed - open/closed messages styling

- _infra/helm/frontstage/Chart.yaml
- frontstage/templates/secure-messages/conversation-view.html
- frontstage/templates/secure-messages/secure-messages-view.html
Couple of issues spotted in secure message due to refactor setup. 
No layout at all on conversation view -> fixed.
Buttons needed updating -> fixed.
Check SM looks ok.
> Fixed buttons and layout on secure message

- _infra/helm/frontstage/Chart.yaml
- frontstage/templates/passwords/forgot-password.check-email.html
- frontstage/templates/passwords/forgot-password.html
- frontstage/templates/passwords/password-expired.html
- frontstage/templates/passwords/reset-password.check-email.html
- frontstage/templates/passwords/reset-password.confirmation.html
- frontstage/templates/passwords/reset-password.html
- frontstage/templates/passwords/reset-password.trouble.html
- tests/integration/test_passwords.py
Refactored the forgot/reset password templates to use design system macros.
Check the journey works ok.
> refactored password journey

- config.py
- frontstage/templates/contact-us.html
- frontstage/templates/errors/400-error.html
- frontstage/templates/errors/403-error.html
- frontstage/templates/errors/403-incorrect-account-error.html
- frontstage/templates/errors/404-error.html
- frontstage/templates/errors/500-error.html
- frontstage/templates/privacy-and-data-protection.html
- frontstage/templates/register/register.activate-account.html
- frontstage/templates/register/register.almost-done.html
- frontstage/templates/register/register.email-resent.html
- frontstage/templates/register/register.enter-enrolment-code.html
- frontstage/templates/register/register.link-expired.html
- frontstage/templates/secure-messages/secure-messages-view.html
- frontstage/templates/secure-messages/thread-message.html
- frontstage/templates/sign-in/sign-in.account-locked.html
- frontstage/templates/sign-in/sign-in.account-not-verified.html
- frontstage/templates/sign-in/sign-in.verification-email-sent.html
- frontstage/templates/surveys/surveys-add.html
- frontstage/templates/surveys/surveys-confirm-organisation.html
- frontstage/templates/surveys/surveys-download-failure.html
- frontstage/templates/surveys/surveys-todo.html
- frontstage/templates/surveys/surveys-upload-failure.html
- frontstage/templates/surveys/surveys-upload-file-picker.html
- frontstage/templates/surveys/surveys-upload-success.html
- frontstage/templates/surveys/surveys.html
- tests/integration/test_registration.py
- tests/integration/views/surveys/test_add_survey.py
Refactored surveys templates to use Design System templates.
All templates/pages under `/surveys`
> Refactored surveys section

- _infra/helm/frontstage/Chart.yaml
- frontstage/templates/secure-messages/messages.html
- frontstage/templates/secure-messages/secure-messages-view.html
- frontstage/templates/surveys/surveys-add.html
- frontstage/templates/surveys/surveys-history.html
- frontstage/templates/surveys/surveys-todo.html
- frontstage/templates/surveys/surveys-upload-file-picker.html
- frontstage/templates/surveys/surveys.html
Small fixes from DAC accessibility review
> Fixes from DAC report

- _infra/helm/frontstage/Chart.yaml
- _infra/spinnaker/deployment-full.json
> syncronize default helm chart

- _infra/helm/frontstage/Chart.yaml
- frontstage/templates/privacy-and-data-protection.html
- frontstage/templates/register/register.enter-your-details.html
- frontstage/templates/secure-messages/conversation-view.html
- frontstage/templates/secure-messages/secure-messages-view.html
- tests/integration/test_cookies_and_contact.py
- tests/integration/test_secure_message.py
> Gdpr advised policy

- .github/workflows/main.yml
- _infra/helm/frontstage/Chart.yaml
- _infra/spinnaker/prodDeploy.json
Update needed to hash in production pipeline, to use template with release parameters.
Also updated GH Actions to ignore Spinnaker changes in build trigger.
- https://collaborate2.ons.gov.uk/jira/browse/RAS-141
> update SHA in prod template, exclude spinnaker from GH triggers

- Pipfile
- Pipfile.lock
- _infra/helm/frontstage/Chart.yaml
- _infra/helm/frontstage/templates/deployment.yaml
- _infra/helm/frontstage/values.yaml
- config.py
- frontstage/controllers/notify_controller.py
- frontstage/views/passwords/reset_password.py
- tests/integration/controllers/test_notify_gateway.py
Convert from old notify to new
> Notify pubsub

- _infra/helm/frontstage/Chart.yaml
- frontstage/controllers/collection_instrument_controller.py
> Update logging and add docstring in controller

- _infra/helm/frontstage/Chart.yaml
- _infra/helm/frontstage/templates/ManagedCertificate.yaml
- _infra/helm/frontstage/templates/backendconfig.yaml
- _infra/helm/frontstage/templates/ingress.yaml
> version updates

- _infra/helm/frontstage/Chart.yaml
- _infra/helm/frontstage/templates/ManagedCertificate.yaml
This was not needed ManagedCert isn't available in v1 of networking yet
> Revert change to ManagedCert

- .github/workflows/comment.yml
- _infra/helm/frontstage/Chart.yaml
> change from sandbox to dev

- config.py
- frontstage/templates/layouts/_base.html
- frontstage/views/sign_in/sign_in.py
CSP script error in Tag Manager code, found during investigations with DST, complains about missing nonce (or alternatives) 
Added missing nonce to script tag in base html template
Deploy to dev, run acceptance tests, check for CSP error
- https://trello.com/c/etrcdyrU
> Fix CSP error for GTagMgr in base

- _infra/helm/frontstage/Chart.yaml
- _infra/helm/frontstage/templates/deployment.yaml
- _infra/helm/frontstage/values.yaml
Helm changes for canary pipeline
> Helm chart changes for canary pipeline

- _infra/helm/frontstage/Chart.yaml
- frontstage/controllers/auth_controller.py
Helm changes for canary pipeline test
> Increasing test error logs by adding additional temp log

- Pipfile
- Pipfile.lock
- _infra/helm/frontstage/Chart.yaml
Werkzeug is at 1.0.1, we should unpin it and fix any issues that come with upgrading it.
Removed werkzeug from Pipfile, and updated Pipfile.lock.
**Local**:
- `make unit-tests`
- `make integration-tests` (ignore temporary redis FLUSHALL errors)
**Dev**:
- deploy to dev and test as usual
- https://trello.com/c/rOTE8qvp
> Unpin werkzeug

- Pipfile
- Pipfile.lock
- gunicorn.py
> updation gnicorn timout and pubsub update

- _infra/helm/frontstage/Chart.yaml
- frontstage/controllers/auth_controller.py
Remove the hardcoded error message to test the canary pass stage
> remove the error

- .github/workflows/comment.yml
- _infra/helm/frontstage/Chart.yaml
> fix namespace

- _infra/helm/frontstage/Chart.yaml
- _infra/helm/frontstage/templates/hpa.yaml
- _infra/helm/frontstage/values.yaml
> add min replicas

- .github/workflows/comment.yml
- _infra/helm/frontstage/Chart.yaml
Use new github action created specifically for ras-rm pr comments.
https://github.com/ONSdigital/ras-rm-spinnaker-action
> new comment action

- _infra/helm/frontstage/Chart.yaml
- frontstage/templates/account/account.html
- frontstage/templates/layouts/configs/service-links.html
- frontstage/views/__init__.py
- frontstage/views/account/__init__.py
- frontstage/views/account/account.py
- tests/integration/views/account/test_account.py
Before this PR, there was no area for users to look at/change create account details.  This is the first of many PRs to enable users to manage these things themselves.
This PR just displays some of the information we have on them already.
> Add user account details page

- _infra/helm/frontstage/Chart.yaml
- frontstage/templates/account/account.html
- frontstage/templates/layouts/configs/service-links.html
The breadcrumb was missing from the prototype (though it isn't styled the same for now).  Also the account link was appearing when the user was logged out.  This has been removed when logged out.
> Add breadcrumb and hide account link when logged out

- _infra/helm/frontstage/Chart.yaml
- frontstage/controllers/party_controller.py
One of the most common error level log lines we see is 'Emails has already been used'.  Logging at the error level should indicate something is wrong and needs to be fixed.  This is not that!
> Reduce client error to info log level

- .github/workflows/main.yml
- Dockerfile
- Pipfile
- Pipfile.lock
- _infra/docker/Dockerfile
- _infra/helm/frontstage/Chart.yaml
> Upgrade python to 3.9

- _infra/helm/frontstage/Chart.yaml
- frontstage/views/secure_messaging/message_get.py
- tests/unit/test_message_get.py
If business name is missing from the business details check "No Business" is rendered in the template
> Check for missing business name

- _infra/helm/frontstage/Chart.yaml
- frontstage/templates/account/account.html
Was adding respondent as request parameter which was making the url really big and erroring out.
took out the respondent as request parameter.
> Adding respondent as request parameter bug fix

- .github/workflows/main.yml
- _infra/helm/frontstage/Chart.yaml
Updating the version to check hoping it to be an intermittent issue.
> Issue with github merge build

- .github/workflows/main.yml
Making changes to min.yaml to check and test git issue
> testing change for github actions issue

- _infra/helm/frontstage/Chart.yaml
> trigger GH Actions following rebuild

- README.md
> Updating readme to test github actions

- frontstage/templates/secure-messages/help/secure-message-send-messages-view.html
Bug secure message send is logging out the user
> Bug secure message logging out

- frontstage/templates/privacy-and-data-protection.html
> Update privacy policy

- .github/workflows/main.yml
> Update version on PR

- README.md
- _infra/helm/frontstage/Chart.yaml
Reverts ONSdigital/ras-frontstage#685
> Revert "Minor readme change"

- .github/workflows/main.yml
- _infra/helm/frontstage/Chart.yaml
The set outputs command needs to run on PR as well
> Fix github actions build

- _infra/helm/frontstage/Chart.yaml
- frontstage/templates/surveys/help/surveys-help-completing-this-survey.html
- frontstage/templates/surveys/help/surveys-help-info-about-this-survey.html
- tests/integration/views/surveys/help/test_surveys_help_info_about_this_survey.py
- tests/integration/views/surveys/help/test_surveys_help_with_this_survey.py
[Trello](https://trello.com/c/4tiP0vNk/541-user-self-serve-remove-sections-of-concern-from-self-help)
> Remove sections of concern from self-help

- _infra/helm/frontstage/Chart.yaml
- frontstage/templates/surveys/help/surveys-help.html
- frontstage/views/surveys/help/surveys_help.py
- tests/integration/views/surveys/help/test_surveys_help_with_this_survey.py
New option was needed on help with survey page to route you to your account help page.  This PR adds that radio button.
> Add help with account radio option

- _infra/helm/frontstage/Chart.yaml
- frontstage/models.py
- tests/integration/views/account/test_password_change.py
Somehow this change was missed in one of the PR. sorry for that
> Validation error message change

- README.md
- _infra/helm/frontstage/Chart.yaml
> Remove unused badges in readme

- _infra/helm/frontstage/Chart.yaml
- tests/test_data/collection_exercise/collection_exercise.json
- tests/test_data/collection_exercise/collection_exercise_before_go_live.json
- tests/test_data/collection_exercise/collection_exercise_list_by_survey.json
- tests/test_data/party/collection_exercises.json
- tests/test_data/surveys_list_eq.json
- tests/test_data/surveys_list_no_trading_as.json
- tests/test_data/surveys_list_seft.json
> Remove casetypes from collection exercise response

- Pipfile.lock
- _infra/helm/frontstage/Chart.yaml
- frontstage/templates/components/button/_macro.njk
- frontstage/templates/components/input/_macro.njk
- frontstage/templates/layout/_template.njk
This is a fix to the templates so that the csp_nonce function can run.
There will be a design system release to provide a solution to the different implementations.
> Updated DS templates to fix csp_nonce issue

- _infra/helm/frontstage/Chart.yaml
- frontstage/templates/components/breadcrumb/_macro.njk
- frontstage/templates/components/button/_macro.njk
- frontstage/templates/components/input/_macro.njk
- frontstage/templates/layout/_template.njk
- scripts/load_templates.sh
Issue observed with upload of SEFT survey. Bug in button js in DS. This PR upgrades to release 31.2.4 of DS that fixes the issue.
Can upload SEFT survey.
https://trello.com/c/qIwvSAIL
> Upgrade to DS v31.2.4 to fix button issue

- _infra/helm/frontstage/Chart.yaml
- frontstage/templates/surveys/surveys.html
Survey history page redesign updates to not show due and updated status colour
https://trello.com/c/yLdj9ZIj/564-user-self-serve-completed-survey-page-design-update
> Survey history page redesign updates

- _infra/helm/frontstage/Chart.yaml
- frontstage/templates/surveys/surveys.html
the logic was not equals to and I marked it as equal to
https://trello.com/c/yLdj9ZIj/564-user-self-serve-completed-survey-page-design-update
> Wrong logic it should have been not equal to

- _infra/helm/frontstage/Chart.yaml
- frontstage/templates/surveys/surveys.html
Bug fix to not show None as due date
https://trello.com/c/yLdj9ZIj/564-user-self-serve-completed-survey-page-design-update
> Survey history redesing bug

- _infra/helm/frontstage/Chart.yaml
- frontstage/controllers/collection_exercise_controller.py
- frontstage/templates/surveys/surveys.html
1. The period covered needs a bigger line height to account for when it goes on to two lines.
2. Removed time from submit by date. Request from business
1. Period covered line-height is 1.2
2. Time is not visible in submit by date
> To do page iteration

- _infra/helm/frontstage/Chart.yaml
- frontstage/templates/layouts/_base.html
- frontstage/templates/layouts/configs/service-links.html
- frontstage/templates/radio-option-select-error-panel.html
- frontstage/templates/surveys/surveys-share/almost-done.html
- frontstage/templates/surveys/surveys-share/business-select.html
- frontstage/templates/surveys/surveys-share/overview.html
- frontstage/templates/surveys/surveys-share/recipient-email-address.html
- frontstage/templates/surveys/surveys-share/send-instructions.html
- frontstage/templates/surveys/surveys-share/survey-select.html
- frontstage/views/account/account_survey_share.py
- tests/integration/views/account/test_account.py
- tests/integration/views/account/test_share_surveys.py
https://trello.com/c/hcTNxy40/637-s32-user-account-creation-share-surveys-content-update
> Share survey content

- _infra/helm/frontstage/Chart.yaml
- frontstage/controllers/party_controller.py
- frontstage/templates/surveys/surveys-share/summary.html
- frontstage/views/account/__init__.py
- frontstage/views/account/accept_share_survey.py
- tests/integration/views/account/test_accept_share_survey.py
- tests/integration/views/account/test_share_surveys.py
https://trello.com/c/3oNFsYdm/482-s34-user-account-creation-share-surveys-holds-account-story-4
https://trello.com/c/3oNFsYdm/482-s34-user-account-creation-share-surveys-holds-account-story-4
> Share survey story 4

- _infra/helm/frontstage/Chart.yaml
- frontstage/controllers/party_controller.py
- frontstage/models.py
- frontstage/templates/register/register-share-survey-enter-your-details.html
- frontstage/templates/register/register-share-survey-registration-complete.html
- frontstage/templates/register/register.enter-your-details.html
- frontstage/views/account/accept_share_survey.py
- frontstage/views/register/enter_account_details.py
- tests/integration/views/account/test_accept_share_survey.py
Share survey story 5
Share survey is excepted once non existing user accepts the share surveys
https://trello.com/c/t8i7o3Pr/481-s35-user-account-creation-share-surveys-does-not-hold-account-story-5
> Share surveys story 5 updates for frontstage

- _infra/helm/frontstage/Chart.yaml
- frontstage/templates/surveys/surveys-share/share-survey-complete-thank-you.html
- frontstage/views/account/accept_share_survey.py
https://trello.com/c/q8rXGb04/721-bug-user-account-creation-sharing-survey-completion-of-sharing
> Adding thank you page for existing account

- Pipfile.lock
- _infra/helm/frontstage/Chart.yaml
- frontstage/templates/components/section-navigation/_macro.njk
> Upgrade flask 2.x

- _infra/helm/frontstage/Chart.yaml
- frontstage/controllers/party_controller.py
- frontstage/models.py
- frontstage/templates/account/account.html
- frontstage/templates/register/register-pending-survey-enter-your-details.html
- frontstage/templates/register/register-pending-survey-registration-complete.html
- frontstage/templates/surveys/surveys-share/business-select.html
- frontstage/templates/surveys/surveys-share/overview.html
- frontstage/templates/surveys/surveys-transfer/almost-done.html
- frontstage/templates/surveys/surveys-transfer/business-select.html
- frontstage/templates/surveys/surveys-transfer/overview.html
- frontstage/templates/surveys/surveys-transfer/recipient-email-address.html
- frontstage/templates/surveys/surveys-transfer/send-instructions.html
- frontstage/templates/surveys/surveys-transfer/share-survey-complete-thank-you.html
- frontstage/templates/surveys/surveys-transfer/summary.html
- frontstage/templates/surveys/surveys-transfer/survey-select.html
- frontstage/templates/surveys/surveys-transfer/transfer-survey-complete-thank-you.html
- frontstage/views/account/__init__.py
- frontstage/views/account/accept_transfer_survey.py
- frontstage/views/account/account.py
- frontstage/views/account/account_survey_share.py
- frontstage/views/account/account_transfer_survey.py
- frontstage/views/register/enter_account_details.py
- frontstage/views/surveys/surveys_list.py
- tests/integration/views/account/test_accept_share_survey.py
- tests/integration/views/account/test_accept_transfer_survey.py
- tests/integration/views/account/test_account.py
- tests/integration/views/account/test_share_surveys.py
- tests/integration/views/account/test_transfer_surveys.py
Frontstage changes for Transfer surveys
https://trello.com/c/tGw1z24M/739-s37-user-account-creation-transfer-of-surveys-transferring-surveys-for-a-respondent-story-1
https://trello.com/c/FwiAgv1H/740-user-account-creation-transfer-of-surveys-registering-transfer-and-sending-emails-story-2
https://trello.com/c/POthNm6U/741-user-account-creation-transfer-of-surveys-routing-and-acceptance-of-surveys-story-3
> Transfer surveys

- _infra/helm/frontstage/Chart.yaml
- frontstage/templates/surveys/help/surveys-help-completing-this-survey.html
- frontstage/templates/surveys/help/surveys-help-info-about-this-survey.html
- frontstage/templates/surveys/help/surveys-help-penalties.html
- frontstage/templates/surveys/help/surveys-help-return-data-by-deadline.html
- frontstage/views/surveys/help/surveys_help.py
- tests/integration/views/surveys/help/test_surveys_help_info_about_this_survey.py
- tests/integration/views/surveys/help/test_surveys_help_with_this_survey.py
user-self-serve iteration story to add panelties and deadline
https://trello.com/c/zUAXLXhv/750-user-self-serve-help-with-a-survey-iteration-story
https://trello.com/c/RGJCLfTX/749-user-self-serve-information-about-a-survey-iteration-story
> user-self-serve iteration story to add panelties and deadline

- _infra/helm/frontstage/Chart.yaml
- frontstage/templates/surveys/surveys-share/send-instructions.html
- frontstage/templates/surveys/surveys-share/summary.html
- frontstage/templates/surveys/surveys-share/survey-select.html
- frontstage/templates/surveys/surveys-todo.html
- frontstage/templates/surveys/surveys-transfer/send-instructions.html
- frontstage/templates/surveys/surveys-transfer/summary.html
- frontstage/templates/surveys/surveys-transfer/survey-select.html
- frontstage/views/account/accept_share_survey.py
- frontstage/views/account/accept_transfer_survey.py
- frontstage/views/account/account_survey_share.py
- frontstage/views/account/account_transfer_survey.py
- tests/integration/views/account/test_share_surveys.py
- tests/integration/views/account/test_transfer_surveys.py
https://trello.com/c/WseJBlY5/776-user-account-creation-handling-multiple-transfers-of-survey
> further changes for transfer surveys

- _infra/helm/frontstage/Chart.yaml
- frontstage/controllers/party_controller.py
- frontstage/templates/surveys/surveys-share/send-instructions.html
- frontstage/templates/surveys/surveys-transfer/send-instructions.html
- frontstage/views/account/account_survey_share.py
- frontstage/views/account/account_transfer_survey.py
- tests/integration/views/account/test_transfer_surveys.py
https://trello.com/c/N7aTNPw7/759-user-account-creation-transfer-and-sharing-surveys-validation-update
> Validation update for duplicate transfer share

- _infra/helm/frontstage/Chart.yaml
- frontstage/templates/surveys/surveys-todo.html
- tests/integration/views/account/test_password_change.py
Minor update of slightly ambiguous text
Port-forward to dev cluster, and run `make test` locally on Frontstage.
- https://trello.com/c/dOmRkcJE
> amend text for adding new survey in to-do

- .github/workflows/main.yml
- _infra/helm/frontstage/Chart.yaml
> Update chart versions automatically

- _infra/helm/frontstage/Chart.yaml
- frontstage/templates/surveys/help/surveys-help-how-safe-is-my-data.html
> Correct puncuation and remove spaces in class

- README.md
- _infra/helm/frontstage/Chart.yaml
- config.py
- frontstage/controllers/auth_controller.py
- frontstage/templates/account/account-delete.html
- frontstage/templates/surveys/surveys-todo.html
- frontstage/views/account/__init__.py
- frontstage/views/account/account_delete.py
- frontstage/views/sign_in/sign_in.py
- tests/integration/controllers/test_auth_controller.py
- tests/integration/mocked_services.py
- tests/integration/views/account/test_account_delete.py
- tests/integration/views/surveys/test_surveys_list.py
https://trello.com/c/h8nV6an7/883-user-account-creation-account-deletion-request
> Delete user account

- _infra/helm/frontstage/Chart.yaml
- frontstage/views/surveys/help/surveys_help.py
> Fix subjects in help

- _infra/helm/frontstage/Chart.yaml
- frontstage/models.py
- frontstage/templates/secure-messages/help/secure-message-send-messages-view.html
- frontstage/templates/secure-messages/help/secure-message-send-technical-messages-view.html
- frontstage/templates/surveys/help/surveys-help-completing-this-survey.html
- frontstage/templates/surveys/help/surveys-help-exemption-completing-survey.html
- frontstage/templates/surveys/help/surveys-help-how-long-selected-for.html
- frontstage/templates/surveys/help/surveys-help-how-safe-is-my-data.html
- frontstage/templates/surveys/help/surveys-help-info-about-the-ons.html
- frontstage/templates/surveys/help/surveys-help-info-about-this-survey.html
- frontstage/templates/surveys/help/surveys-help-info-something-else.html
- frontstage/templates/surveys/help/surveys-help-my-survey-is-not-listed.html
- frontstage/templates/surveys/help/surveys-help-penalties.html
- frontstage/templates/surveys/help/surveys-help-return-data-by-deadline.html
- frontstage/templates/surveys/help/surveys-help-something-else.html
- frontstage/templates/surveys/help/surveys-help-specific-figure-for-response.html
- frontstage/templates/surveys/help/surveys-help-time-to-complete.html
- frontstage/templates/surveys/help/surveys-help-who-is-the-ons.html
- frontstage/templates/surveys/help/surveys-help-why-selected.html
- frontstage/templates/surveys/surveys-todo.html
- frontstage/templates/surveys/surveys.html
- frontstage/views/surveys/__init__.py
- frontstage/views/surveys/help/surveys_help.py
- frontstage/views/surveys/help/technical_help.py
- frontstage/views/surveys/surveys_list.py
- tests/integration/views/surveys/help/test_surveys_help_info_about_the_ons.py
- tests/integration/views/surveys/help/test_surveys_help_info_about_this_survey.py
- tests/integration/views/surveys/help/test_surveys_help_something_else.py
- tests/integration/views/surveys/help/test_surveys_help_with_this_survey.py
- tests/integration/views/surveys/help/test_technical_help_survey_not_listed.py
* S43a User Self Serve - Where is my survey "to do" page link
* S44 Incorrect subject in frontstage help page
* Incorrect bread crumb name
https://trello.com/c/cjGG7F01/930-s43a-user-self-serve-where-is-my-survey-to-do-page-link
https://trello.com/c/ctakC5Zu/941-s44-incorrect-subject-in-frontstage-help-page
https://trello.com/c/CoewPFZG/957-incorrect-bread-crumb-name
> Survey not listed on todo tab and refactor

- Pipfile.lock
- _infra/helm/frontstage/Chart.yaml
- _infra/helm/frontstage/templates/deployment.yaml
- _infra/helm/frontstage/values.yaml
- frontstage/common/validators.py
- frontstage/models.py
- frontstage/views/account/account_survey_share.py
- frontstage/views/account/account_transfer_survey.py
- frontstage/views/register/enter_account_details.py
- frontstage/views/sign_in/sign_in.py
Prod is currently running on Dev config - we need to be able to set this by environment
https://trello.com/c/tbb3yi0u/1022-ensure-ras-frontstage-is-correct-in-prod-startup
> Change Helm chart to take config type

- _infra/helm/frontstage/Chart.yaml
- _infra/helm/frontstage/values.yaml
- config.py
> changed config and values to point to mock eq in dev

- _infra/helm/frontstage/Chart.yaml
- _infra/helm/frontstage/templates/service.yaml
> Remove flag for backendconfig linkage

- _infra/helm/frontstage/Chart.yaml
- _infra/helm/frontstage/templates/ManagedCertificate.yaml
Adding managed cert for production and going to v1
> Adding a managed cert from production

- _infra/helm/frontstage/Chart.yaml
- _infra/helm/frontstage/values.yaml
> Make frontstage limits more sensible

- _infra/helm/frontstage/Chart.yaml
- _infra/helm/frontstage/templates/ingress.yaml
> GCP Managed Cert

- _infra/helm/frontstage/Chart.yaml
- _infra/helm/frontstage/templates/ManagedCertificate.yaml
- config.py
- frontstage/models.py
- frontstage/templates/account/account-change-email-address-conflict.html
- frontstage/templates/account/account-change-email-address.html
- frontstage/templates/account/account-contact-detail-change.html
- frontstage/templates/account/account-email-change-confirm-link-expired.html
- frontstage/views/account/account.py
- frontstage/views/account/account_email_change.py
- tests/integration/views/account/test_account.py
- tests/integration/views/account/test_account_email_change.py
https://trello.com/c/qHvQrOWt/512-s48-user-account-creation-change-own-email-address
> account-email-changes update

- _infra/helm/frontstage/Chart.yaml
- frontstage/templates/account/account-change-email-address.html
- tests/integration/views/account/test_account.py
https://trello.com/c/qHvQrOWt/512-s48-user-account-creation-change-own-email-address
> small but with respect to text

- _infra/helm/frontstage/Chart.yaml
- frontstage/views/register/create_account.py
> Add more metadata to existing logging

- _infra/helm/frontstage/Chart.yaml
- _infra/helm/frontstage/templates/deployment.yaml
- _infra/helm/frontstage/values.yaml
- config.py
- frontstage/templates/account/account.html
- frontstage/views/account/account.py
The feature flag for this is switched on in every environment and it'll never be switched off.  This PR removes that flag.
> Remove TECHNICAL_MESSAGE_ENABLED feature flag

- .github/workflows/main.yml
- Dockerfile
- Pipfile
- Pipfile.lock
- README.md
- _infra/docker/Dockerfile
- _infra/helm/frontstage/Chart.yaml
> Upgrade python to 3.10

- _infra/helm/frontstage/Chart.yaml
- frontstage/views/surveys/download_survey.py
- frontstage/views/surveys/upload_survey.py
https://trello.com/c/fppK4TTA/1253-bug-investigate-ras-frontstage-upload-download-validation-not-working
> Validation raises no survey permission error if the validation fails

- _infra/helm/frontstage/Chart.yaml
- frontstage/views/surveys/download_survey.py
- frontstage/views/surveys/upload_survey.py
https://trello.com/c/fppK4TTA/1253-bug-investigate-ras-frontstage-upload-download-validation-not-working
> Bug fix seft validation

- _infra/helm/frontstage/Chart.yaml
- frontstage/templates/cookies.html
https://trello.com/c/btMLGPRa/1302-cookies-policy-wording-alterations-to-support-v3-eq
> updating cookie policy

- Pipfile.lock
- _infra/helm/frontstage/Chart.yaml
- frontstage/common/eq_payload.py
- tests/integration/test_generate_eq.py
https://trello.com/c/o2MsO0Gr/1300-fix-eq-v3-payload-issues
> fixing timestamp format issue for response_expires_at

- _infra/helm/frontstage/Chart.yaml
- frontstage/templates/surveys/surveys-todo.html
- tests/integration/views/surveys/test_surveys_list.py
https://trello.com/c/4Pqofk7l/1362-frontstage-enrolment-code-wording
> frontstage enrolment code wording

- _infra/helm/frontstage/Chart.yaml
- frontstage/common/eq_payload.py
- frontstage/controllers/case_controller.py
- tests/integration/test_generate_eq.py
https://trello.com/c/2YkV9EQ7/1388-add-responseid-while-launching-eq-v3
> Adding response_id for EQ v3

- Pipfile
- Pipfile.lock
- _infra/helm/frontstage/Chart.yaml
> Unpin python-gnupg

- .github/workflows/comment.yml
- .github/workflows/main.yml
- _infra/helm/frontstage/Chart.yaml
- frontstage/templates/secure-messages/conversation-list.html
- frontstage/templates/secure-messages/conversation-view.html
The html injection on secure massage list has been fixed by wrapping the table body with <xmp> tag.
https://trello.com/c/t1NAhJ8a/1514-pen-test-html-injection
> Fixing html injection on message conversation list

- _infra/helm/frontstage/Chart.yaml
- frontstage/common/cryptographer.py
- frontstage/controllers/party_controller.py
- frontstage/views/register/confirm_organisation_survey.py
- frontstage/views/register/enter_account_details.py
Added more logging around the enrolment code pages to give us more hints if the encrypted enrolment code param isn't getting passed for whatever reason.
Also improved the documentation and removed a function that wasn't being called by anything.
> Add more logging around enrolment code process

- README.md
- _infra/helm/frontstage/Chart.yaml
- _infra/helm/frontstage/templates/externalsecrets.yaml
> Remove gpg from instrument service

- _infra/helm/frontstage/Chart.yaml
- frontstage/controllers/auth_controller.py
> Slightly improve logging on failed login attempt

- _infra/helm/frontstage/Chart.yaml
- frontstage/templates/layouts/_base.html
> Adding banner link

- _infra/helm/frontstage/Chart.yaml
- frontstage/templates/layouts/_base.html
remove memorial banner
https://trello.com/c/3RLkhbpi/2044-remove-memorial-banner
> remove hardcoded memorial banner

- .flake8
- .github/workflows/main.yml
- Dockerfile
- Pipfile
- Pipfile.lock
- README.md
- _infra/docker/Dockerfile
- _infra/helm/frontstage/Chart.yaml
> Upgrade to python 3.11 and update action version

- .github/workflows/main.yml
- _infra/helm/frontstage/Chart.yaml
Removal of deprecated github action
https://trello.com/c/JyPxSmDA/2298-replace-soon-to-be-deprecated-set-output-in-github-actions
> Fix setoutput

- Pipfile.lock
- _infra/helm/frontstage/Chart.yaml
- frontstage/templates/surveys/surveys-access.html
Adding a couple of lines to help inform the user about which files to download and upload when responding to a SEFT survey.
- Deploy this pr to your environment
- Run the acceptance tests tagged as SEFT
- Ensure that the new lines of text appear when in the SEFT survey
https://trello.com/c/SidH5mOt/2341-update-seft-download-and-upload-pages-wording
> Updating SEFT wording for respondents

- _infra/helm/frontstage/Chart.yaml
- frontstage/templates/layouts/_base.html
- frontstage/templates/partials/ga.html
- frontstage/templates/partials/gtm-no-script.html
- frontstage/templates/partials/gtm.html
Remove non javascript code and update 
This isn't really possible to test in dev, bar checking that the non javascript code doesn't appear anymore in the html. The reason you can't really test any further is because we don't have a tag manager id for dev only preprod
N.B you will need to give the env GOOGLE_TAG_MANAGER_ID a value in config or export it otherwise nothing will appear
> RAS-857 Remove GA4 <noscript>, change analytics cookie key

- _infra/helm/frontstage/Chart.yaml
2 PRs went in fairly quickly and although the rebase was fine, it didn't pick up that the release number needed increasing
> Manually update version

- .github/workflows/codeql-analysis.yml
- _infra/helm/frontstage/Chart.yaml
This PR updates the deprecated version of CodeQL, also removes an warning message when setting up the python dependencies. 
Check output of the codeQL run against this PR. 
https://jira.ons.gov.uk/secure/RapidBoard.jspa?rapidView=1493&projectKey=RAS&view=detail&selectedIssue=RAS-907
> Update CodeQL to v2

- .github/workflows/main.yml
- _infra/helm/frontstage/Chart.yaml
Replacing the unmaintained create release action with a github command that does the same and updating the setup-gcloud
Check the build
https://jira.ons.gov.uk/browse/RAS-1011
> RAS-1011 Replace unmaintained actions/create-release and update google-github-actions/setup-gcloud

- Pipfile.lock
- _infra/helm/frontstage/Chart.yaml
Bump requests-mock dev package to bump idna to 3.7
> Upgrade requests-mock to bump idna to 3.7

- .github/workflows/main.yml
- Makefile
- _infra/helm/frontstage/Chart.yaml
Signed pr-bot commits and have ignored 2 vulnerabilities where there are currently no fixes for.
> Have added bot signature and have added additional CVE ignore

- Pipfile.lock
- _infra/helm/frontstage/Chart.yaml
Update Gunicorn to 23.0.0
Check everything still works
> RAS-1258 Update Gunicorn frontstage to 23.0.0

- _infra/helm/frontstage/Chart.yaml
[RAS-1322](https://jira.ons.gov.uk/browse/RAS-1322)
> Updating version

- _infra/helm/frontstage/Chart.yaml
- frontstage/controllers/party_controller.py
- tests/test_data/party/respondent_enrolments.json
> Transfer survey fix

- frontstage/common/authorisation.py
- frontstage/templates/contact-us.html
- frontstage/views/contact_us.py
- tests/unit/views/test_cookies_and_contact.py
This PRs makes the contact_us page dynamic on whether a respondent is authorised or not
Go to the contact us page, when logged in and logged out
> RAS-1198 Contact us (after log in)

- frontstage/templates/account/account-delete.html
- frontstage/views/account/account_delete.py
- tests/integration/views/account/test_account_delete.py
Updates the delete account to the new design
Check the delete account still works
> RAS-1201 Delete an account

- _infra/helm/frontstage/Chart.yaml
- frontstage/templates/surveys/surveys-add.html
Fix the link from the add survey page to secure messaging
Make sure the link now works
> RAS-1529 Need help with enrolment code - Send Message link

- _infra/helm/frontstage/Chart.yaml
- _infra/helm/frontstage/templates/ingress.yaml
This PR reverts the update made to the ingress GCE class while a permanent fix can be looked at. 
Check it reverts the ingress change in this PR
https://github.com/ONSdigital/ras-frontstage/pull/1048
https://jira.ons.gov.uk/browse/RAS-1377
> Undo deprecation update

- _infra/helm/frontstage/Chart.yaml
- frontstage/common/session.py
- frontstage/controllers/conversation_controller.py
- frontstage/views/secure_messaging/message_get.py
- frontstage/views/sign_in/sign_in.py
- frontstage/views/surveys/access_survey.py
- frontstage/views/surveys/surveys_list.py
- frontstage/views/surveys/upload_survey.py
- frontstage/views/surveys/upload_survey_failed.py
- tests/integration/controllers/test_conversation_controller.py
- tests/integration/test_jwt_authorization.py
- tests/integration/test_secure_message.py
- tests/integration/test_session.py
This code removes the secure message count being called and stored in redis
Make sure the application works as before
> RAS-1539 Remove secure message count from frontstage

- _infra/helm/frontstage/Chart.yaml
> Bump to 2.5.55

- _infra/helm/frontstage/Chart.yaml
- frontstage/views/help.py
Allow handing of base help route
> Allow handing of base help route on top of 2.5.67
