ONSdigital/ras-frontstage

app/templates/secure-messages-draft.html
What is the context of this PR:
Fixed a bug that caused additional whitespace to be added when editing a previously saved draft.
Trello Card - [https://trello.com/c/i9HKtkQq](https://trello.com/c/i9HKtkQq)
How to review:
Create a draft then click in the text area when editing and see if the cursor goes half way down the second line.
=> fixed added whitespace

app/common/post_event.py, app/config.py, app/templates/surveys/surveys-access.html, app/views/post_event.py, app/views/register.py, app/views/sign_in.py, app/views/surveys.py, scripts/run.sh, tests/test_account_activation.py, tests/test_app.py, tests/test_registration.py, tests/test_surveys.py
Ok, this is a cut-down PR designed to integrate case-service event logging only. However (!) in order for this to work, it *needs* to have consistent data, to this end the patch includes inserting a party_id in the JWT on login.
This code contains the 'beginnings' of the static routing PR, but is limited to changes in **config.py** and the new **post_event.py** file.
- The party_id inserted into the JWT is a hard-coded value from the agreed cross-site test data and said id designed to facilitate end-to-end testing of login/upload/download. This party_id *should* come from a party service lookup by email address - when the party service provides that facility.
=> Cut-down case service code only

app/views/sign_in.py, config.py, scripts/run.sh, tests/test_app.py, tests/test_data/my_party.json, tests/test_surveys.py
Adds a simple lookup to recover a party_id from the party service based on the requested login id (email address) and inserts that party_id into the JWT in place of the previously hard-coded id.
=> Adding code to recover party_id from party service by email address

frontstage/views/sign_in.py
I've kept the templates in case these end up being useful at some point
=> removing unused sign-in endpoints

frontstage/views/secure_messaging.py
This PR fixes the 500 error draft save (Trello cards - https://trello.com/c/6DBcxJRi & https://trello.com/c/ShZt86uH) 
To test create a new draft with an error in subject and body, save, then resolve the error and when you save test that it doesn't go to 500 error page.
=> Fixed 500 error on draft save

config.py, frontstage/views/info.py
When services are deployed a file is automatically generated called git_info which contains latest info for the info endpoint.
These changes should allow the info endpoint to look at that file and return the data, alongside the `NAME` and `VERSION` at the info endpoint
=> settings NAME and VERSION by environment variables

frontstage/views/secure_messaging.py, requirements.txt
Adding `"Content-Type": "application/json"` to the headers for requests to secure-messaging
=> added content-type to secure messaging post requests

frontstage/logger_config.py
Setting default logging to be json formatted across one line.
You can set the environment variable `JSON_LOGGING_INDENT=1` to enable indented json logs locally
=> adding choice of indented or one line json logs

frontstage/logger_config.py
The logger was handling the indent variable as a string rather than an int. The new code now forces this to be an int or none.
=> Making logging indent config more stable

frontstage/logger_config.py, frontstage/views/register.py
When a user tries to register an account with an email address that has already been used we no longer throw a 500 error. It is handled in the same way as the rest of the form validation
=> Adding error handling for duplicate email

frontstage/views/sign_in.py, tests/test_sign_in.py
Handle 404 response from party service on sign-in so it doesnt just throw a 500 error
=> allowing sign-in form to fail more gracefully

frontstage/templates/register/register.link-expired.html, frontstage/views/register.py, tests/app/test_account_activation.py
Removed the code around resending a verification email for an expired token.
I've left the removed code commented as it should work once ras-party changes have been made.
Along with this I've updated the templates to match what is in defect 30 https://trello.com/c/lPXVBZmZ/595-defect-30-story-us008-verify-new-account-8-a-500-error-is-displayed-not-the-message-to-contact-the-ons-to-request-a-new-link-fou
=> removing resending email functionality

frontstage/templates/register/register.confirm-organisation-survey.html, frontstage/templates/register/register.enter-enrolment-code.html
BRES respondents won't already have an account, so have removed this from the "Create account - Enrolment code" and "Confirm organisation and survey" pages.
Due to the current P1, you won't be able to view "Confirm organisation and survey" page in the browser, but can test that I've removed the content in the html.
=> Removed 'already got account?' content

frontstage/templates/partials/footer.html
Without alt text, the image in the footer failed accessibility compliance.
Added "OGL" as alt text.
=> Accessibility - Changes to html in footer

frontstage/views/register.py
Removing company name and survey name from the `enter-your-details` template.
This didn't require any functional change as the arguments were not being used anyway
https://trello.com/c/G6zZ9ICL/666-company-name-is-exposed-in-url-query-string
=> removing org/survey name from url

frontstage/templates/secure-messages/secure-messages-create.html
Replying to a message in external generates Bad_request failure
https://trello.com/c/xGExW55k/660-defect-62-story-found-in-release10-replying-to-a-message-in-external-generates-badrequest-failure
Thread id hidden field was missing from secure-messages-create.html
=> Added hidden input field thread id

frontstage/templates/passwords/reset-password.html
Show password toggle added to form in same way as sign-in page.
To test you can comment out lines 56-66 in `passwords.py` and got to the 
`/passwords/reset-password/aaa` endpoint
=> Adding show password toggle to password-reset form

frontstage/templates/sign-in/sign-in.account-not-verified.html
Incorrect message when the trying to login without verifying the account.
- Added ons email
- Remove 'help with email' section
https://trello.com/c/kERbocRp/675-defect-47-us007-found-in-release-80-sit-incorrect-message-when-the-trying-to-login-without-verifying-the-account
=> Add ons email and remove help with email

frontstage/templates/register/register.confirm-organisation-survey.html
Added surveys.ons.gov.uk as an option if details not as expected, for people who prefer to email rather than use the phone.
Also, the international number had been put in with the leading 0 after the country code, which may have cause a problem for anyone using the link.
Added the nowrap class so phone number remains on one line.
=> Added email address and corrected international number

frontstage/templates/secure-messages/message-form.html
No visual changes, but html no longer has <fieldset> tag in it wrapped around the form input fields because not necessary (and previous version had fieldset with no legend which failed accessibility).
=> Removed fieldset tag from secure message form

frontstage/views/secure_messaging.py
Previously frontstage was overriding sending the jwt to frontstage api with basic auth.
Fixed so they send separately
=> fixing conflict between jwt and basic auth

tests/app/test_logger_config.py
Tests for the `logger_config.py` file already existed in ras-frontstage-api. This just moves them over to frontstage to improve test coverage
=> Add logger-config-tests

config.py, tests/app/test_secure_message.py, tests/app/test_surveys.py
These changes work with the accompanying "add-namespaces" PR in Frontstage-api https://github.com/ONSdigital/ras-frontstage-api/pull/18
Tests also had to be updated to work with these changes
=> Change api url endpoints to use namespaces

frontstage/jwt.py
The last PR shouldn't have removed this, worrying that it wasn't caught by the tests we should look to add new ones which will cover this.
For now need this as a fix
=> Add expires_at field to jwt that was removed accidentally

frontstage/templates/passwords/reset-password.html, frontstage/templates/sign-in/sign-in.html, frontstage/templates/sign-in/sign-in.last-attempt.html
The show password was removed for release 14 as the value was being cache by the browser, meaning on a shared computer this would be an issue. 
This story adds it back in, but stops the browser caching it. I have checked autocomplete works on all browsers that GDS requires using browser stack (https://www.browserstack.com/)
https://www.gov.uk/service-manual/technology/designing-for-different-browsers-and-devices
=> Restore show password and add autocomplete false

frontstage/templates/surveys/surveys-access.html, frontstage/templates/surveys/surveys.html, tests/app/test_surveys.py, tests/test_data/surveys_list.json
Uses the ["user visible name"](https://github.com/ONSdigital/rm-collection-exercise-service/blob/master/API.md#example-json-request-body-1) (from the collection exercise) in a survey page title and "period covered" in survey lists (historic and todo).
NB: Additional test data provided to check title is rendered as expected in unit tests.
=> Tbl129 ensure correct survey and ce values displayed to respondents

frontstage/views/__init__.py, frontstage/views/secure_messaging/create_message.py, frontstage/views/secure_messaging/message_get.py, tests/app/test_secure_message.py
RU_REF, CASE_ID and Survey were all missing from the template so were not sent by the frontstage application.
Case ID is now also optional in secure messaging so doesn't always need to be sent
=> Fix reply to message

frontstage/views/secure_messaging/message_get.py
The send save draft message fails as the ru_ref and survey are not in the create message url and this PR fixes that issue
However this whole function seems incorrect, certain values are picked from the message json while others from the draft json. Looking at ras-frontstage api it is not using the draft endpoint in secure message in this scenario. I think we should create separate routes in the UI for sending new messages and sending draft messages.
=> Send draft message fix

frontstage/common/authorisation.py, frontstage/views/sign_in/sign_in.py, tests/app/test_sign_in.py
This PR fixes a bug where authorization tokens are not having their expiry set in the client's browser.
=> Set expiry on auth token

frontstage/templates/secure-messages/thread-message.html
Bug Fix:
When the external user looked at a message from the internal user, it would not add any line breaks for the message.
This fix just adds a span for the message body to allow line breaks
=> Message from internal now has line breaks

frontstage/templates/secure-messages/secure-messages.html
Bug fix:
On the messages page on frontstage, inbox counter would not update the message once the read full message link had been clicked.
fixed it by changing the label of the message once the link had been clicked.
=> Fixed read full message link

frontstage/views/surveys/access_survey.py, tests/app/test_surveys.py
As part of defect-r-16-13-stop-mulitple-eq-access a 403 can now be return from frontstage-api. As there was no ability to catch anything other then a 200 I have added one in
=> Catch status codes other then 200 in access survey

frontstage/assets/js/modules/validators.spec.js, frontstage/static/js/bundle.js
Allowing the hash symbol to be accepted in the password to stop the client side error message appearing when a hash is entered in the password. This has now been extended to add other special characters that are missing.
=> adding hash to symbols for password

frontstage/models.py, tests/app/test_registration.py
When submitting an email address with whitespace in the account registration the application gives a 500 error. This PR adds validation to the email address to check if there is whitespace and gives an error to the user.
=> Adding validation on email address for whitespace

frontstage/controllers/conversation_controller.py
ras-frontstage uses Session (http://docs.python-requests.org/en/master/user/advanced/) to get retry functionality if a HTTP request fails. When a Session is created the TCP connection is continued to be reused which leads to long running/open TCP connections. Cloundfoundry may do some housekeeping and close long running TCP connections incase they are connection that haven't correctly been closed. If that connection is closed it should reconnect but we're not experiencing this behaviour gracefully when running the services in CF. (https://docs.cloudfoundry.org/services/route-services.html)
All of the above was causing us to experience 500 errors occasionally when sending messages.
Instead of creating one session at the beginning when the application starts we will now create a new session …
=> Fix secure message usage of requests session

frontstage/common/eq_payload.py, tests/app/test_generate_eq.py, tests/test_data/collection_exercise/collection_exercise_events.json
Some of the last changes added into https://github.com/ONSdigital/ras-frontstage-api were missed off and not ported into this code base in #333. This PR brings those orphaned changes in.
Ported changes from:
- ONSdigital/ras-frontstage-api#66
- ONSdigital/ras-frontstage-api#67
Follow the PR's listed above for further information, run the tests, and check that the code does what it says on the tin.
=> Port missing api eq functionality

Pipfile.lock, frontstage/common/message_helper.py, frontstage/controllers/party_controller.py, tests/app/test_jwt_authorization.py, tests/app/test_message_helper.py
The Business have been informed that the time stamp for secure messaging doesn't reflect BST.
Time displayed for users in secure message is BST
Run RAS/RM, send a message to an internal user, the message should display the correct time
=> Output time to match BST timezone in secure message

Pipfile, Pipfile.lock
pipenv on the Cloud Foundry buildpack is giving the following error:
In --require-hashes mode, all requirements must have their versions pinned with ==.
These do not: greenlet>=0.4.13; platform_python_implementation == "CPython" from
https://files.pythonhosted.org/packages/dd/ce/7b3a19a3eb8c79e6237ba1fb7a8729b39034dd2de8753b8d27e5abc59fd5/greenlet-0.4.13-cp36-cp36m-manylinux1_x86_64.whl\#sha256\=42118bf608e0288e35304b449a2d87e2ba77d1e373e8aa221ccdea073de026fa
(from gevent==1.3.0->-r /tmp/app/.cloudfoundry/0/requirements.txt (line 14))
This rolls back some of the changes made in https://github.com/ONSdigital/ras-frontstage/commit/2446bbe96a51760e945cce7aa4263ca9b7a2eca9
Acceptance tests only on this one
=> Fix changes to Greenlet in pipfile

frontstage/models.py, frontstage/templates/errors/validation_error.html, frontstage/templates/register/register.enter-enrolment-code.html, frontstage/views/register/create_account.py
Currently when a user enters an enrolment code longer or shorter than 12 character, nothing happens. This introduces validation on that error. Also we were counting leading/trailing white spaces as characters, so this PR stops that also.
Run Frontstage enter an enrolment code too long/short and view validation error, try with spaces they shouldn't count
=> Add validation for enrolment code length

frontstage/error_handlers.py, frontstage/templates/partials/business_survey_credentials.html, frontstage/templates/register/register.confirm-organisation-survey.html, frontstage/templates/surveys/surveys-confirm-organisation.html, frontstage/views/register/confirm_organisation_survey.py, frontstage/views/surveys/add_survey_confirm_organisation_survey.py
To fix a current op issue and to stop us getting calls about this when we ramp up from respondents.
Card: https://trello.com/c/QSXFlFjU/233-ext-display-the-ru-trading-as-name-if-it-has-one-on-the-confirm-organisation-page-linked-to-a-current-ops-issue-s
- Run and check that when you add a new survey using an enrolment code that for that survey it displays the trading as name if present and check for one that does not have a trading as name as well to check if it displays correctly.
- Check tests pass as usual.
=> Update confirm organisation page to display RU trading name if present

frontstage/templates/register/register.confirm-organisation-survey.html, frontstage/templates/surveys/surveys-confirm-organisation.html, frontstage/views/register/confirm_organisation_survey.py, frontstage/views/surveys/add_survey_confirm_organisation_survey.py
When confirming business details after entering an enrolment code, get a 500 because enrolment code in template was returning empty string.
template to read enrolment code properly
try to register an account or add a survey
=> Templates to use enrolment code

frontstage/templates/passwords/forgot-password.check-email.html, frontstage/templates/passwords/forgot-password.html, frontstage/views/passwords/forgot_password.py, tests/app/test_passwords.py
Current defect where the forgot password page has an incorrect message displayed to the user when they submit an unregistered email address
Card: https://trello.com/c/M8KCuVwm/235-ext-defect-us012-forgot-password-has-incorrect-message-when-user-submits-an-unregistered-email-address-m
Check that the correct content is displayed on the password reset page as well as validation when you enter a non valid email address as well on the forgot password screen.
=> Defect - Forgot password has incorrect message when user submits an unregistered email address

Pipfile.lock
for some reason the jwcrypto libs has not hashes in the Pipfile.lock, so this has been regenerated
Pipfile.lock
=> update the project deps, specifically to generate hashes for jwcrypto

.gitignore, Pipfile, Pipfile.lock, README.md, config.py, frontstage/create_app.py
Motivation and Context
==
Currently there's no way to trace the requests through the application.
This will add the tracing headers to any request that comes through this
application onto another service, or preserve existing headers allowing the user
to follow requests through the application as a whole.
There are also new configuration settings:
```
| ZIPKIN_DISABLE                  | Totally disable Zipkin (including tracing headers)            | False
| ZIPKIN_DSN                      | Zipkin Sample API URL (e.g. http://zipkin:9411/api/v1/spans)  | None
| ZIPKIN_SAMPLE_RATE              | Percentage of requests to send to zipkin span API             | 0
```
By default this will add the tracing headers, but make no requests to Zipkin's neat little UI.
No visible functional changes, …
=> ZipKin Tracing

frontstage/logger_config.py, tests/app/test_logger_config.py
Currently there's no way to trace the requests through the application.
This will add the trace and span IDs into all log statements.
Run unit and acceptance tests.
https://trello.com/c/5cYDTILb/156-add-the-zipkin-correlation-and-span-id-into-the-logs-for-python-services-2d
=> Add Zipkin IDs to logs.

Pipfile.lock
orderedmultidict has a new wheel associated to the same versioned app in
pypi. This causes pipenv or pip to fall over when validating the hashes
of the package are correct. Regenerating the lock file should resolve
this.
=> Regenerate lock file

Pipfile, Pipfile.lock
Pipenv lock did not add jwcrypto hashes into the Piplock.file.
Re doing it after updating pipenv and clearing cache.
Explicitly specify jwcrpto package in Pipfile
Tests should pass
=> Fix missing jwcrypto hashes

frontstage/templates/secure-messages/secure-messages-view.html
On frontstage, when creating a secure-message the respondent was able to enter in more than 10,000 characters in to the body of the message. This would cause a `Something went wrong ` page to appear when trying to send a message and it would be blocked by WAF. This PR adds a max length to the text box to stop this happening.
- Added a max length to the secure message body text box
- Attempt to type more than 10,000 characters and the text box should stop you from doing so
- All tests pass
- Acceptance tests pass with the respective branch ([Acceptance tests branch](https://github.com/ONSdigital/rasrm-acceptance-tests/pull/174))
[Trello card](https://trello.com/c/1Oga8Jnv/317-frontstage-secure-message-rejected-by-waf-if-the-body-is-too-long)
=> 317 updating secure message text box

.vscode/settings.json, frontstage/templates/layouts/_base.html, frontstage/templates/register/register.almost-done.html
Bug observed with the guidance component where the content was hidden when JS was disabled. It should be displayed.
On the "Almost done..." page when signing up, there was a cut off of content on the guidance component.
The no js bug has been fixed in the pattern library and released (v1.5.6). The version has been changed to get the latest code.
A utility class to add a margin to the guidance component fixes the cutting off issue.
Test the component with no js and ensure the element isn't cut off and is visible.
=> Changed cdn version to latest (v1.5.6)

frontstage/logger_config.py, tests/app/test_logger_config.py
Align tracing names in log with Java services.
=> Align trace naming.

Pipfile, Pipfile.lock
Remove pycrypto which has been flagged as security vulnerability with newer and more maintained pycryptodome.
=> Change pycrypto dependency to better maintained pycryptodome

frontstage/controllers/party_controller.py, frontstage/templates/register/register.link-expired.html, frontstage/views/register/activate_account.py, frontstage/views/sign_in/sign_in.py, tests/app/test_sign_in.py
If a respondent attempts to use an expired verification token (older than 80 hours) then they have to phone us and request to be sent another link.  This change allows respondents to resend the verification link to their email.
- Amended the page that is displayed when users attempt to us an expired link, giving them the option to send another.
- Call to a new endpoint in party to use the expired token to send another mail.
- Added tests.
- Run against branch`206-resend-verification-if-using-expired-link` in ras-party.  Ensure that `EMAIL_TOKEN_EXPIRY` is set to 0 in party so that the links immediately expire when manually testing.
- Using the new link to resend the verification email should generate a new verification link - check in party logs.
- All tests should pass.
- …
=> Allow a verification link to be resent if using an expired one

config.py, frontstage/common/eq_payload.py, tests/test_data/eq_payload.json
EQ have implemented the logout facility so redirect to our logout page, but they need us to provide the url to redirect to. Although we already pass the location of the todo list we also need to do this as well with another variable we can pass to logout to the relevant page.
Adding in a new variable to pass in the payload to EQ to logout from EQ & RAS to the signed out page.
A new env has also been introduced to Jenkins for this as well.
Ensure AT pass etc.
Trello Card: https://trello.com/c/6Bfd2jlB/382-logout-ras-rm-from-eq-m
=> Logout RAS RM from EQ

frontstage/controllers/party_controller.py, frontstage/templates/passwords/password-expired.html, frontstage/templates/passwords/reset-password.check-email.html, frontstage/views/passwords/reset_password.py, tests/app/test_passwords.py
When a respondent requests a change of password, they are emailed a link that expires after 80 hours.  If they try to use the link after the 80 hours then they are redirected to a page that tells them to phone us for another link.  This PR allows the respondent to generate a new link which is then sent to the email registered to their account.
New and amended pages to allow a user to resend a password reset link if the one they attempt to use has expired. 
- All unit tests should pass
- Set the EMAIL_TOKEN_EXPIRY in party config to -1 so that tokens expire as soon as they're created (otherwise you'll be waiting 80 hours for one to expire)
- Run this branch alongside `207-resend-password-reset-link-if-expired` in ras-party
- In frontstage, request a password reset for an active account - …
=> 207 resend password reset link if expired

.travis.yml, frontstage/controllers/oauth_controller.py, frontstage/controllers/party_controller.py, frontstage/exceptions/exceptions.py, frontstage/views/passwords/forgot_password.py, tests/app/test_passwords.py
A call to authentication service was introduced as a way to stop locked users to reset their password in [PR230](https://github.com/ONSdigital/ras-frontstage/pull/230).
The requirements around this has changed so locked users can now reset their password and unlock
their account (changed logic in django-oauth-test [PR46](https://github.com/ONSdigital/django-oauth2-test/pull/46) ). Which now makes the call to the django-oauth-test service redundant.
Removed the call to django-oauth-test for send reset password email
Ran AT and check you can still reset your password for both locked and unlocked account.
=> Remove unnecessary auth call

frontstage/static/css/theme.css
Bug fix required for survey listing page. The access survey button broke the grid on medium screen size between 745 -> 960. See screenshot below:
The width value has been removed from the `button` so the text can wrap correctly. See screenshot below:
Check that the button doesn't break out of the grid when the browser in resized.
https://trello.com/c/UZH0y6TA/346-xbrowser-testing-for-cdn-implementation
=> Fixed issue with survey access button breaking outside grid

frontstage/controllers/case_controller.py
We now only have one case for each casegroup so we no longer have to filter down to just one
Removed code doing unnecessary filtering.
Unit/Acceptance tests should pass
Survey list can still be loaded
[Trello](https://trello.com/c/wpEG5uL2/343-remove-code-in-frontstage-to-filter-for-one-case-in-case-group-once-multiple-b-cases-per-case-group-are-removed)
=> Remove unnecessary code filtering cases for survey list

frontstage/controllers/party_controller.py, frontstage/templates/surveys/surveys.html, tests/app/controllers/test_party_controller.py
Only display access survey button for eQ when: 
- notstarted, 
- inprogress,
- reopened
Above
Change casegroup status and see if button disappears
=> Only display access survey button for eQ when:

frontstage/controllers/case_controller.py
In response-operation-ui, we want to be able to see the respondent name on the responses status page when a external user has completed a collection exercise. For this to happen, Frontstage needs to post a case event with metadata containing the party_id of the respondent. This can then be used for the response status page.
- Changed party_id to metadata when posting case event message
- Run `mvn clean install` and it should build successfully
- Run with the [case-svc-api PR](https://github.com/ONSdigital/rm-casesvc-api/pull/33), [R-ops branch](https://github.com/ONSdigital/response-operations-ui/tree/us211-display-respondent-for-seft-rus-ce-in-response-status), [Case service PR](https://github.com/ONSdigital/rm-case-service/pull/100) and complete a SEFT collection exercise. When …
=> posting metadata to case service

frontstage/common/eq_payload.py
When Collection exercise event dates are added through Response-Ops, they are converted to UTC prior to being stored and are converted back to local time to be displayed on the collection exercise page, which is all good.
Frontstage retrieves the collection exercise dates to form part of the eq_payload but doesn't convert the dates from UTC. We only send the date part of the date/time string and this has resulted in us passing incorrect dates to eQ.
Doing `.asTimeZone()` brings the iso8601 parsed date back from UTC to the server local timezone
This isn't testable unless the server local timezone isn't UTC. If you fancy testing it in late March you go wild.
=> Convert utc to local

config.py, frontstage/common/authorisation.py, frontstage/templates/sign-in/sign-in.html, frontstage/views/sign_in/sign_in.py, tests/app/test_jwt_authorization.py, tests/app/test_message_get.py, tests/app/test_sign_in.py
When a user clicks a link from an email, it would come up with an `JWTValidation` saying the user must sign in. What we want to happen is though, for the user to click the link and be directed to the sign in page. When they sign in they then get brought to the requested page they wanted.
- User now gets redirected to sign in page when attempting to visit a page which requires a login.
- Split up login method as it was too complex
- Send a message from internal to external. When trying to visit that conversation when not signed in, you should be brought to the sign in page. When signed in, you should be redirected to the conversation.
[Trello](https://trello.com/c/nLsI8fjn)
=> 582 redirect user to page requested after sign in

config.py, frontstage/templates/surveys/surveys-todo.html, frontstage/views/surveys/add_survey_submit.py, frontstage/views/surveys/surveys_list.py, tests/app/mocked_services.py, tests/app/views/surveys/test_add_survey_submit.py, tests/test_data/associations.json, tests/test_data/case/case_diff_surveyId.json
Makes the use case scenario with a respondent using a new enrolment code to add a survey they have already added more friendly.
Added a check to see if the user is already enrolled before making the database requests, prevents 500 error.
Run acceptance tests on the already_added_survey_test branch
Acceptance Test PR: https://github.com/ONSdigital/rasrm-acceptance-tests/pull/239
https://trello.com/c/gfNFRVsR/569-569-add-validation-for-respondents-adding-another-survey-to-their-enrolment
=> 'You have already added that survey' Message

config.py, frontstage/controllers/case_controller.py, tests/app/controllers/test_case_controllers.py, tests/app/mocked_services.py, tests/test_data/case/case_list_without_iac_and_with_case_events.json
To try and make the to-do page even quicker, an IAC boolean is passed to the case service to say if we want it added to the case or not. Passing in false will skip a DB call which should make things quicker.
- Pass in IAC boolean to case service
- Run with [Case service PR](https://github.com/ONSdigital/rm-case-service/pull/105)
- Run with Acceptance tests
- Open up the todo page and make sure everything is working such as accessing survey and completing it.
[Trello](https://trello.com/c/5xsPP92s)
=> Add ability to fetch cases without IAC codes

config.py, frontstage/templates/surveys/surveys-todo.html, frontstage/views/surveys/add_survey_submit.py, frontstage/views/surveys/surveys_list.py, tests/app/mocked_services.py, tests/app/views/surveys/test_add_survey.py, tests/app/views/surveys/test_add_survey_submit.py, tests/test_data/associations.json, tests/test_data/case/case_diff_surveyId.json
Didn't work before, now it does.
Added true/false unit tests for the check to see if a user is already enrolled
Made a change to the check which removed unexpected behaviour (preventing people from enrolling who should be able to.)
1) Run the unit tests for add_survey_submit.py
2) Try and enrol to a survey on a users account that they are already enrolled to using a new enrolment code (should fail and show Already added survey' message).
3) Try and enrol to a survey that the user is not enrolled on (should succeed and show survey added message).
https://trello.com/c/gfNFRVsR/569-569-add-validation-for-respondents-adding-another-survey-to-their-enrolment
=> Already added survey message fix

frontstage/controllers/party_controller.py, tests/app/controllers/test_party_controller.py
The verbose parameter is optional when calling the party service, but for some reason, we've hardcoded it to always be true.  In the future we might want to call this function without the verbose mode, so this allows us to do so.
We also improved the unit tests around this area of code slightly.
The way the parameters are passed has been refactored.  Now it uses requests build in parameters argument, which takes a dictionary.  It means we don't have to build the whole url and it's easy to add new parameters if we need to (otherwise we end up having to handle the ? and & characters, which is a huge hassle).
Run the unit tests, they should still pass.
The acceptance tests can also be run, but as the functionality is identical (all we did was add an optional variable and default it to true), …
=> Configurable verbose

.travis.yml, frontstage/controllers/party_controller.py, tests/app/controllers/test_party_controller.py
Ras frontstage was erroring in the case where a user was enrolled on a collection exercise but that collection exercise had not started .  
The error was due to using enrolment survey id as an index into collection exercises , but collection exercises were restricted to those that had started . 
Changed the generator to not consider enrolments where the collex had not yet started . 
Run unit tests . 
https://trello.com/c/W59SAyNd
=> restricted enrolments as seen in the UI to those for started collex

frontstage/templates/passwords/forgot-password.check-email.html
There is a typo on frontstage which shows the email address 'surveys.ons@gov.uk' - this has been altered to read 'surveys@ons.gov.uk'.
Email address changed in both href and content of markup.
Confirm change in code, run solution, confirm change shows up.  Make sensible checks that nothing is adversely affected.
https://trello.com/c/F51uuYXO
**NB: This is actually Adam Wilkie's first PR, I'm just submitting it for him because his machine is out of battery**
=> Fixed typo in email on password reset page

frontstage/views/register/enter_account_details.py, tests/app/test_registration.py
When signing up an account on RAS Frontstage, the user arrives at the same URL before and after entering their email address, with different content on the page.
For best URL practice, and for ease of analytics, make the confirmation page appear at a separare URL
Email confirmation page now appears at a different URL
* Sign up a respondent account
* Confirm that the 'check your email' page appears at a separate page URL
* Check that acceptance tests pass
=> Change url for confirm email

frontstage/templates/register/register.enter-your-details.html
Very occasionally, a user double clicks the submit button on the frontstage sign up form, which creates two accounts for them on the system.
Whilst this shouldn't be possible in party, it was agreed in planning that this was a good mitigation, whilst a ticket would be raised to prevent this in party or the schema later.
* Form onsubmit event is bound to a function that will only allow submission once.
Click the button twice, and note whether the form submits twice in logs.
Run acceptance tests.
https://trello.com/c/J4xky7nK
=> Added JS to disable form after first submit

frontstage/common/validators.py, frontstage/models.py, tests/test_validators.py
The use of HTML5 input attributes like `required` prevents the user experience being in line with that desired.
* Wrote custom validators that extend WTForm validators and removes html5 attribs
* Imported these validators in form models, instead of the WTForm validators
* Wrote tests
* Run through process of signing up as a respondent and confirm that in source code, no input has `required` attribute (can do this using inspect element)
* Run through other forms in frontstage, do the same check
* Acceptance tests
https://trello.com/c/lPtTcThh
=> Remove html5 attribs from forms

Pipfile, Pipfile.lock, tests/app/controllers/test_survey_controllers.py
There are multiple vulnerable packages.  This PR fixes them, but pins redis to 2.X as the upgrade to 3.X breaks some functionality.
Nothing that a user can see.  Various packages have been updated and redis has been pinned to ensure it keeps on working.
Unit tests should still pass.
Acceptance tests should pass (on my run, 1 failed but it looked unrelated when I tested the functionality).  I had to check out the tag for frontstage as one of the tests fell over when I had a local copy running (as opposed to a docker container)
Use frontstage yourself, it should still all work as expected.
https://trello.com/c/swUJ0rJf/810-fix-ras-frontstage-package-security-issue-2
=> Fix ras frontstage package security issue

frontstage/templates/errors/400-error.html
Fixed a small error in the title of https://github.com/ONSdigital/ras-frontstage/pull/443
Page title is now correct for a status code 400 page (previous one referenced 404)
Get to an error page.  Check the title is sensible.
https://trello.com/c/k1M7FJAy/844-csrf-returning-as-500-on-frontstage
=> Fix 400 error page title

frontstage/static/css/theme.css, frontstage/templates/passwords/reset-password.html, frontstage/templates/sign-in/sign-in.html
The purpose of this push was to make sure the "show password" option on the sign-in page is hidden if javascript was disabled. Before now, the show password option would appear, but would be non-functional if javascript was disabled. This change makes the interface less misleading to users who don't use javascript.
- Added a .hide-if-no-js function to theme.css.
- Applied the .hide-if-no-js to the "show password" boxes in both sign-in.html and reset-password.html.
- Switch off javascript in your browser (in Chrome, click the three dots in the top-right, go into "settings", then "advanced" at the bottom, then "site settings", then "javascript", then disable javascript).
- Load the sign-in page in frontstage (port 8082) and see if the "show password" box appears above the password field. It …
=> added no-js to hide show password if javascript disabled

frontstage/controllers/conversation_controller.py, frontstage/error_handlers.py, frontstage/exceptions/exceptions.py, frontstage/templates/errors/403-incorrect-account-error.html, tests/app/test_secure_message.py
Added a template for when a user follows a direct link to a secure message for an account other than the one they are logged in to.
This is so that users with multiple respondent accounts aren't confused as to why they cant access a message.
Added page template
Created new exception which results in a page render
Implemented unit tests for new functionality
Run frontstage unittests
Can manually test by sending a message to a respondent, grabbing the link from frontstage and trying to access it after logging into another account.
https://trello.com/c/iWD6OxY9/824-403-message-thread-not-found-status-page-3
=> 403 message thread not found status page

frontstage/templates/errors/403-incorrect-account-error.html
Fixes bug in https://github.com/ONSdigital/ras-frontstage/pull/456 that went to the wrong href
Put the correct relative HREF in
Load up frontstage
Navigate to `/templates/errors/403-incorrect-account-error.html`
Check the hours aren't on that page any more and a link to the contact page appears instead
Make sure the link follows through to the contact page
=> Fix the link on the new 403

frontstage/templates/errors/400-error.html, frontstage/templates/errors/500-error.html
So that we can track 400 and 500 errors independently in google analytics
added - 400 to the 400 template title, this is what our user researcher deemed most appropriate.
hit the error and look at the title
https://trello.com/c/JllhbBP2/1069-400-and-500-page-both-using-the-same-title-1
=> appended '- 400' to the 400 error page title for distinction from 500 in analytics

frontstage/views/secure_messaging/message_get.py, tests/app/mocked_services.py, tests/app/test_secure_message.py
The remove v2 endpoint change for secure message had a side effect that old emails stopped working correctly as /thread was changed to /threads
/thread/<thread_id> and /threads/<thread_id> now hit the same endpoint, whereas before hitting /thread/<thread_id> would cause an error as that endpoint doesn't exist anymore.
- Unit tests pass
- Ensure that thread in fronstage can be accessed using both /thread and /threads urls (just change it manually after accessing it the first time)
=> Fix broken /thread links in emails

frontstage/controllers/oauth_controller.py
The auth service has been changed to return both title and message in json . This uses the title in the exception generations
Uses title from response
run acceptance tests
https://trello.com/c/XpfbLBNw
=> Use error message from auth

Pipfile.lock, tests/app/controllers/test_collection_instrument_controller.py
sdc-cryptography has a new version that we should be using.
- Packages updated with pipenv lock, resulting in a number of packages being updated as well as the one we specifically wanted.
- Collection instrument test updated as it was failing.
Unit and acceptance tests still pass.
https://trello.com/c/hmQQabr6
=> Update sdc crypto

frontstage/templates/errors/500-error.html
The link was pointing to the main ONS contact page rather than SDC
The link points to the right place
Visit the 500 error page and check it goes to the right place
=> Put the right link in

frontstage/routes.md
Turns out that an endpoint marked as unused *is* used internally. This documents that.
=> Update docs to reflect that an endpoint is used

Makefile, config.py, frontstage/__init__.py
It used to map to 7379 , docker was moved to 6379 to ease testing , this is following 
changed testing config
run acceptance tests
=> Move redis to port 6379

frontstage/views/surveys/surveys_list.py
Currently the todo and history list sort the list of surveys with the oldest first.  This isn't a big deal when there are a handful of surveys, but with a long list, you'll have to scroll down quite a far way to see your latest surveys. 
The todo and history are sorted with newest first, as opposed to oldest first.
- Run the acceptance tests to put in some example data.  Then sign in as a respondent.  The newest surveys should be at the top.  For extra checking, you can enrol on another survey and see that it's added to the right place in the list
https://trello.com/c/VRjWyzVd
https://trello.com/c/63o99Lx6
=> Newest first survey list

frontstage/controllers/party_controller.py, tests/app/controllers/test_party_controller.py, tests/test_data/party/collection_exercises.json
Currently we get the live collection exercises for the user for the todo and history lists.  These never go away so the list gets longer and longer.  This PR filters the surveys from the live surveys list if the end date (which is a date far in the future from the return by date) to make the list be full of relevant surveys.
Note:  The collection exercise service has the concept of not-started and live surveys only.  In the future, if it ever becomes a list of 3 (not-started, live-but-not-ended and ended) then the filter done here can be removed and we can change the call to collection exercise with the data we care about.
- Added code to filter out the ended surveys from the list.
- Unit and acceptance tests pass.
- Spin the service up (with seeded data from accecptance tests), change …
=> Filter ended collection exercises out of lists

frontstage/routes.md, frontstage/views/register/enter_account_details.py, tests/app/test_registration.py
When creating an account, the enter account details page will redirect via a GET request a confirm email route. This redirection includes the email as a url parameter. This needs to be remove, so we're going to render the template immediately in the enter account details page instead, as it has all the information anyway.
Modified enter_account_details.py to stop it redirecting when you create an account, instead we immediately render the template.
1. Find an unused enrolment code
1. Create a new account
1. Account should be created successfully and the Almost done page should be rendered with the email from the step above.
https://trello.com/c/sx7LBxf8/1422-stop-email-address-being-passed-as-a-url-parameter-in-frontstage-3
=> Render template on POST

frontstage/views/passwords/reset_password.py
Before, the password reset link would be `/passwords/reset-password/<token>`
This PR fixes so that it becomes `http://localhost:8082/passwords/reset-password/<token>`
=> Append the protocol and host to reset link

_infra/helm/frontstage/Chart.yaml, _infra/helm/frontstage/templates/backendconfig.yaml, config.py, frontstage/create_app.py
When running behind a GCP load balancer with SSL termination use the HTTP_X_FORWARDED_PROTO header to set the protocol scheme on the WSGI middleware.
If this is not set then flask will redirect all requests back to http.
=> Add fix for load balancer ssl termination in GCP

Makefile
Disabled 'pipenv check' in Makefile, pending resolution of blocking pipenv bugs 2412 (plus duplicates) and 4147
Commented the line 'pipenv check' in the Makefile, with a note to uncomment as soon as possible.
https://trello.com/c/3ZxIpfsX
=> temporarily disabled pipenv check, pending pipenv bug resolution

_infra/helm/frontstage/templates/backendconfig.yaml
allows for session affinity based on client ip
added a tag within the backendconfig for session affinity
i can't test it but when it is merged and deployed it will show up in advanced config for backend services
=> added session affinity for Client IP to backendconfig.yaml file

_infra/helm/frontstage/Chart.yaml, _infra/helm/frontstage/templates/deployment.yaml, _infra/helm/frontstage/values.yaml
Allowing the selection of different version numbers will allow code changes to be tasted without needing to commit to master.
- Added if-statement in `deployment.yaml` to select version number based on the presence of the `latest` tag in `values.yaml`.
- Updated chart version number.
- Added `latest` tag to `values.yaml`.
[Trello card](https://trello.com/c/Xlj2T6Gi)
=> made changes to deployment, values, and chart.yaml

_infra/helm/frontstage/templates/ManagedCertificate.yaml, _infra/helm/frontstage/templates/ingress.yaml, _infra/helm/frontstage/values.yaml
The gcp dns is no longer required. we use the aws dns surveys.onsdigital.uk
=> remove the redendant dns

_infra/helm/frontstage/templates/deployment.yaml, _infra/helm/frontstage/values.yaml
The helm charts needed to have the option of selecting different repos when a developer is testing changes.
- The `deployment.yaml` now switches to the devRepo if the `latest` tag is not set.
- Added the devRepo to `values.yaml`. As of now, it is the same as the current image's repo, but will be different in prod and pre-prod.
[Trello card](https://trello.com/c/fLbRN0qG)
=> added devRepo

frontstage/templates/layouts/_base.html
Fix missing checkbox for card "S7 Migration testing - No 'show password' check box displaying on external pre prod."
added missing csp_nonce to base layout
make test
https://trello.com/c/7bqJUuX2
=> added csp_nonce to fix missing password checkbox

frontstage/views/sign_in/sign_in.py
CSRF and Secure cookies break chrome tests, firefox doesnt have the same issues. This is due to chrome following their own standards and not RFC. By controlling secure cookies and csrf by the WTF_CSRF_ENABLED flag we can test the basic functionality of the frontend with acceptance tests
=> Local test fix

_infra/helm/frontstage/templates/deployment.yaml, _infra/helm/frontstage/templates/ingress.yaml, _infra/helm/frontstage/values.yaml, config.py, frontstage/create_app.py
http traffic will always give us the google 404 error, which will confuse external users.
By forcing https in talisman we can ensure that we are always redirected to https. Our HSTS headers will ensure all all subsequent redirects happen at the browser level preventing any man in the middle attacks.
The httpsOnly annotation needs to be removed in order to allow http traffic at the loadbalancer
=> force https and allow http traffic at the loadbalancer

frontstage/__init__.py, frontstage/create_app.py, frontstage/views/info.py, tests/app/views/surveys/test_download_survey.py
recent change to fronstage allowed http traffic but a redirect is necessary for http traffic.
This failed the kubernetes health checks as every /info hit was being redirected to https.
=> separate talisman to allow health checking

_infra/helm/frontstage/templates/deployment.yaml, _infra/helm/frontstage/values.yaml, config.py, frontstage/controllers/collection_instrument_controller.py, tests/app/controllers/test_collection_instrument_controller.py
The final part of the security review suggested setting the access control origin header to our domain during SEFT downloads. 
I've matched the header to the ingress host when deployed in kubernetes and to * when run locally.
Additional header has been set. 
Test added to check error
1. Run the application
1. Ensure you have a respondent that is able to download a SEFT survey
1. Download a seft survey and check that the access control header is correct. (NB. I found this easier to check in firefox)
https://trello.com/c/STxexCYI/1834-s7-access-control-allow-origin-header-3
=> Access Control Origin Header

Pipfile.lock, _infra/helm/frontstage/Chart.yaml, frontstage/routes.md, frontstage/views/surveys/access_survey.py, tests/integration/test_generate_eq.py, tests/integration/views/surveys/test_access_survey.py
A while ago we moved a bunch of urls from having _ to -.  To reduce the risk we allowed both versions for a while to make sure nothing was using the old version.
That was 10 months ago and after looking at preprod, everything uses '-' so we should start removing these extra urls and the extra test code to handle both cases.
=> Remove deprecated survey url

_infra/helm/frontstage/Chart.yaml, frontstage/routes.md, frontstage/views/surveys/upload_survey_failed.py, tests/integration/views/surveys/test_upload_survey_failed.py
A while ago we moved a bunch of urls from having _ to -. To reduce the risk we allowed both versions for a while to make sure nothing was using the old version.
That was 10 months ago and after looking at preprod, everything uses '-' so we should start removing these extra urls and the extra test code to handle both cases.
=> Remove upload_failed endpoint and update dates

.github/workflows/main.yml, Makefile, _infra/helm/frontstage/Chart.yaml, frontstage/common/authorisation.py, frontstage/common/session.py, frontstage/controllers/conversation_controller.py, frontstage/error_handlers.py, frontstage/jwt.py, frontstage/static/css/theme.css, frontstage/templates/partials/tab_list.html, frontstage/views/secure_messaging/create_message.py, frontstage/views/secure_messaging/message_get.py, frontstage/views/sign_in/logout.py, frontstage/views/sign_in/sign_in.py, frontstage/views/surveys/access_survey.py, frontstage/views/surveys/add_survey_submit.py, frontstage/views/surveys/download_survey.py, frontstage/views/surveys/surveys_list.py, frontstage/views/surveys/upload_survey.py, frontstage/views/surveys/upload_survey_failed.py, tests/integration/controllers/test_conversation_controller.py, tests/integration/mocked_services.py, tests/integration/test_generate_eq.py, tests/integration/test_jwt_authorization.py, tests/integration/test_secure_message.py, tests/integration/test_session.py, tests/integration/test_sign_in.py, tests/test_data/secure_messaging/count.json
Add an unread message count to the current session.
Controllers that render a new page will get the unread message count from the sessio with the exception of the signin page and the view conversation route. These calls must hit the api directly.
When the secure-message api returns a count, the session will be updated with the new information and will be timed for 10 minutes, after 10 minutes the count will refresh with another query to the secure message api.
Changed SessionHandler to Session. The session object will has several factory methods and convenience functions. Session logic has been taken out of the controllers. The session object can be persisted by calling `session.save()`. Renamed the `update_session` function to `refresh` as it was only renewing the expiry time of the jwt, …
=> add session logic for unread messages

Pipfile, Pipfile.lock
vulnerability in `rsa` requires fixing. pipenv check fails.
=> add latest rsa for vulnerability fix:wq

_infra/helm/frontstage/Chart.yaml, frontstage/templates/layouts/_base.html
Availaibility message is outside grid and so displays incorrectly.
Moved inside grid.
Wrong:
Correct:
=> Moved availaibility message inside grid

_infra/helm/frontstage/Chart.yaml, frontstage/common/message_helper.py, frontstage/controllers/conversation_controller.py, frontstage/controllers/iac_controller.py, frontstage/views/secure_messaging/create_message.py, frontstage/views/secure_messaging/message_get.py, frontstage/views/surveys/access_survey.py, frontstage/views/surveys/add_survey_confirm_organisation_survey.py, frontstage/views/surveys/add_survey_submit.py, tests/integration/mocked_services.py, tests/integration/test_secure_message.py
There was an endpoint that has been deprecated since September 2019.  We left the endpoint to handle the transition but it's been 9 months so we're certainly not sending emails with the old url.
Also found various spacing things to fix and a few .formats that could turn into f-strings.
Also updated a few functions to have docstrings
=> Remove deprecated endpoint

_infra/helm/frontstage/Chart.yaml, frontstage/models.py, frontstage/templates/secure-messages/conversation-view.html, frontstage/templates/secure-messages/secure-messages-view.html, tests/integration/test_secure_message.py
The message body character limit needed to be increased to 50000.
* Changed validation checks to allow for messages of up to 50000, instead of 10000, as it used to be.
Try entering a message of over 10000, and check that it validates
[Jira card](https://collaborate2.ons.gov.uk/jira/browse/RAS-16)
[Related secure message PR](https://github.com/ONSdigital/ras-secure-message/pull/308)
=> changed message body character limit to 50000

_infra/helm/frontstage/Chart.yaml, _infra/helm/frontstage/templates/ingress.yaml, frontstage/create_app.py
Changes to the backend config to remove X-FORWARD-Proto (not supported) and relying on scheme config value to setup the `wsgi.url_scheme`.
=> Replacing X-FORWARDED-PROTO custom header

_infra/helm/frontstage/Chart.yaml, frontstage/templates/vunerability_disclosure.html
Add hackerone hyperlink for users to be able to navigate to the correct submission page in our vulnerability disclosure policy.
Fix typo
=> fix typo and add hyperlink to hackerone

_infra/helm/frontstage/Chart.yaml, _infra/helm/frontstage/templates/deployment.yaml, _infra/helm/frontstage/values.yaml, config.py, frontstage/controllers/auth_controller.py
Add a config for generating errors in a canary. This will allow us to continue tweaking and testing new canary configs without having to release a new version of frontstage each time
=> add test errors by setting config

_infra/helm/frontstage/Chart.yaml, _infra/helm/frontstage/templates/ingress.yaml
A new certificate has been created and uploaded to GCP.
the cert name is `surveyrenew`
Change the annotation here to update the ingress to use the new cert.
=> change certificate name

_infra/helm/frontstage/Chart.yaml, frontstage/templates/account/account-change-email-address.html, frontstage/templates/account/account-contact-detail-change.html, frontstage/views/account/account.py, tests/integration/views/account/test_account.py
Making changes for https://trello.com/c/rKk4XdJA/364-s27-user-account-creation-change-own-email-address to keep it as it is with prototype.
=> changing to comply with prototype

_infra/helm/frontstage/Chart.yaml, frontstage/templates/secure-messages/conversation-view.html, frontstage/templates/secure-messages/secure-messages-view.html, tests/integration/test_secure_message.py
Altered wording to bring this up to date with current version of "change own account details" story.
Updated wording of a sentence each in conversation view and secure messages view
Deploy to dev cluster. Go to "To-do" and click "Send a message". The form should now match the mockup in the story [Privacy notification update to secure messaging platform](https://collaborate2.ons.gov.uk/confluence/pages/viewpage.action?pageId=42295192#Useraccountcreation(RAS/RM)-RAS-235), and clicking the link in the new sentence should take you to the Account Details form.
- https://trello.com/c/aKRRIooz
- https://github.com/ONSdigital/ras-frontstage/pull/662
=> update change-own-account wording

_infra/helm/frontstage/Chart.yaml, frontstage/controllers/banner_controller.py, tests/integration/controllers/test_banner_controller.py
If the banner service was unavailable, the whole of frontstage would fail.  With this PR, we handle the case of a connection error more gracefully so the show can continue even if the banner is unavailable
=> Return empty string if banner service unavailable

_infra/helm/frontstage/Chart.yaml, tests/integration/test_passwords.py
The call to notify wasn't mocked so the test took forever to run (and time out).  This PR mocks 1 and fixes another test to bring the runtime of the integration tests from 2min15secs to about 10secs
=> Mock email sending so test is instant

_infra/helm/frontstage/Chart.yaml, frontstage/models.py
Missed special character in regex. Thinking about it.. there could be any special character hence removing regex and using the existing way of validating password.
=> Bug fix for password change

_infra/helm/frontstage/Chart.yaml, frontstage/views/surveys/surveys_list.py, tests/integration/views/account/test_password_change.py
One of the password change tests had a warning that there was a missing mocked.  This was around the survey list screen.  Tried to mock the urls but there were too many.  Instead this replicates (roughly, I'm returning a list rather then a generator) what the `get_survey_list_details_for_party` function returns to bypass the need to mock a bunch of stuff
=> Fix integration test that missing mocked urls

.github/workflows/main.yml, _infra/helm/frontstage/Chart.yaml
During the release step tag the generated docker image as both the release version and latest.
=> Docker tag latest at the same time as the release

_infra/helm/frontstage/Chart.yaml, frontstage/common/message_helper.py, frontstage/views/secure_messaging/create_message.py, frontstage/views/secure_messaging/message_get.py, frontstage/views/surveys/help/surveys_help.py, tests/test_data/collection_instrument/collection_instrument_eq_no_eq_id.json, tests/test_data/collection_instrument/collection_instrument_eq_no_form_type.json, tests/test_data/conversation_list.json, tests/test_data/message.json, tests/test_data/secure_messaging/message.json, tests/test_data/secure_messaging/messages_list_inbox.json, tests/test_data/secure_messaging/thread.json, tests/test_data/secure_messaging/thread_no_party.json
Create a database script to standardise the naming convention in secure message service.
run in dev
S33 RASRM database rationalisation - Secure Message
=> Standardise fieldname on secure message 

_infra/helm/frontstage/Chart.yaml, frontstage/templates/register/register-pending-survey-enter-your-details.html, frontstage/templates/register/register.enter-your-details.html, tests/integration/test_registration.py
Fixed issue with not retaining user information after a single validation failure on account registration
https://trello.com/c/soD3v81b/821-retain-data-on-account-sign-up-screen-when-error-has-been-made
=> Fixed issue with not retaining user information after a single

_infra/helm/frontstage/Chart.yaml, frontstage/views/surveys/help/surveys_help.py, tests/integration/views/surveys/help/test_surveys_help_info_about_the_ons.py, tests/integration/views/surveys/help/test_surveys_help_something_else.py
On 2 of the something else pages (info about the ons -> something else, and something else -> something else) if you didn't put any text in the message, it would Error in an ugly way instead of just showing a standard validation error.
This PR fixes this by making sure the breadcrumbs are correctly set up on error.  There are also tests for the offending pages to make sure it doesn't regress.
=> Fix error message on 'something else' pages

Pipfile, Pipfile.lock, _infra/helm/frontstage/Chart.yaml, frontstage/controllers/collection_instrument_controller.py, tests/integration/mocked_services.py
2 things
- Modify the endpoint used to get the collection instrument to the simplier `/<id>` form.
- Update packages as there was a security vulnerability in `pycryptodome`
=> Modify collection instrument call

_infra/helm/frontstage/Chart.yaml, _infra/helm/frontstage/templates/backendconfig.yaml, _infra/helm/frontstage/values.yaml
User with a very large number of businesses was seeing k8s timeouts to get the todo page. Adding a configurable timeout so we can temporarily fix the issue.
=> Add configable ingress timeout

_infra/helm/frontstage/Chart.yaml, _infra/helm/frontstage/templates/backendconfig.yaml
Frontstage doesn't define a backendconfig in production as it's historically been used to set the security policy to make sure that authorised IPs can access it (which is the case in rops preprod and prod, and preprod frontstage).
This PR creates a backendconfig if it's public (inversing the logic that was there before) and locking down the backend if the environment is anything other then prod.
=> Modify backendconfig depending on environment

_infra/helm/frontstage/Chart.yaml, _infra/helm/frontstage/templates/ingress.yaml
Using a google managed cert now, so this can be remove
=> Remove the old pre-shared cert

_infra/helm/frontstage/Chart.yaml, frontstage/common/eq_payload.py, tests/test_data/collection_exercise/collection_exercise_events.json
There's a new optional field in the EQ payload called response expires at. For EQ v3 we need to provide this field, equal to the collection exercise end date in ISO_8601 format
https://trello.com/c/mQbYzg2o/1129-s48-eq-v3-support-response-expires-at
=> Support 'Response Expires At'

_infra/helm/frontstage/Chart.yaml, frontstage/controllers/party_controller.py
The performance of the todo page was pretty slow in places.  One of the slowest parts was when it gets all the collection instruments.  It was asking for way more instruments then it could possibly need as it would do the following:
- Get all the businesses the respondent is part of
- Get all the cases that business is part of
- Get all the collection instruments for every case the business is part of (This bit is slow and includes cases for collection exercises that have ended as well as ones the respondent might not be involved with).
I've changed the algorithm so it only gets the instruments it needs by doing the following:
- Get all the businesses the respondent is part of
- Get all the cases the business is part of
- Figure out which cases the respondent is part of (which is …
=> Get smaller number of collection instruments

_infra/helm/frontstage/Chart.yaml, _infra/helm/frontstage/templates/deployment.yaml, _infra/helm/frontstage/values.yaml, config.py, frontstage/templates/account/account.html, frontstage/views/account/account.py
The share surveys feature is turned on in all environments.  This PR removes the feature flag that isn't needed anymore
=> Remove share surveys flag

_infra/helm/frontstage/Chart.yaml, frontstage/controllers/party_controller.py, frontstage/views/surveys/surveys_list.py, tests/integration/controllers/test_party_controller.py
In the survey list page, party was called twice to get the respondent data.  This is reasonably expensive because party has to spend time figuring out associations, enrolments, etc.
This PR makes the call once and passes the respondent returned to the 2 places that it needs it.  This should shave off about 400ms~ off the time it takes to load the survey list
As part of this, I unbound some of the logging as it was being applied to every log line in the survey list process, even if it was an empty value (and would never have a value).  This is a bit of a quick tidy up and could be looked at in the future once we have some data and can figure out what we need.
=> Change survey list to get respondent only once

Dockerfile
The upgrade to python 3.10 is incompatible with the version of pipenv that was pinned in this dockerfile.  Unpinning it should fix the build issue
=> Modify dockerfile

_infra/helm/frontstage/Chart.yaml, frontstage/common/eq_payload.py, frontstage/controllers/case_controller.py, frontstage/controllers/party_controller.py, frontstage/views/surveys/download_survey.py, frontstage/views/surveys/upload_survey.py, tests/integration/controllers/test_case_controllers.py, tests/integration/views/surveys/test_download_survey.py, tests/integration/views/surveys/test_upload_survey.py
The `is_respondent_enrolled` function had a weird return type where it could be either a boolean or a dict.  This is bad practice so this PR modifies that function and everything that uses it to only care about the value returned
=> Refactor 'is_respondent_enrolled' function

_infra/helm/frontstage/Chart.yaml, frontstage/common/encrypter.py, frontstage/controllers/case_controller.py, tests/integration/controllers/test_case_controllers.py
For collection exercises created before the concept of eq versions, the eqVersion field is null (which translates to None).  Before this PR, if it was empty then it'll raise an error.  With this PR, if it's blank then we can assume it's v2 and treat it as such.
=> Count missing eq version as v2

Pipfile.lock, _infra/helm/frontstage/Chart.yaml, frontstage/common/redis_cache.py, frontstage/controllers/party_controller.py, tests/integration/controllers/test_party_controller.py
Changing where the business party cache is stored, in the common redis cache rather than in instance cached_data. This is to match what has been done with survey and collection instrument
=> Implement business party caching

Pipfile.lock, _infra/helm/frontstage/Chart.yaml, frontstage/common/redis_cache.py, frontstage/controllers/party_controller.py, tests/integration/controllers/test_party_controller.py
Changing where the collection exercise cache is stored, in the common redis cache rather than in instance cached_data. This is to match what has been done with survey and collection instrument and business party, also the population of enrolments has been changed since it used the entire collex dictionary
=> Implement collection exercise caching

_infra/helm/frontstage/Chart.yaml, frontstage/controllers/collection_exercise_controller.py
If you're signed up for a survey that has no live collection exercise then collection when you try and load the survey list, you'll see an error.
This is because collection exercise gives a 204 with no content when there aren't any (which is correct).  The code takes a successful response then does `response.json()` to it.  For a 200 response this works fine, but if you do that when theres no content it complains.
We'll simply change it so that if it's a 204 then just return an empty list to represent nothing.
- Create collection exercise in response ops (with a quick end date)
- Make it live
- Enrol for that collection exercise as a respondent (optional: and verify it appears in your survey todo list)
- Wait for the collection exercise to end
- Try and load your todo list page again. …
=> Return empty list if there are no live exercises

_infra/helm/frontstage/Chart.yaml, config.py, frontstage/templates/account/account-change-password.html, frontstage/templates/passwords/reset-password.html, frontstage/templates/register/register-pending-survey-enter-your-details.html, frontstage/templates/register/register.enter-your-details.html, frontstage/templates/sign-in/sign-in.html, frontstage/views/account/account.py, frontstage/views/sign_in/logout.py, frontstage/views/sign_in/sign_in.py, tests/integration/test_passwords.py, tests/integration/views/account/test_accept_share_survey.py, tests/integration/views/account/test_accept_transfer_survey.py, tests/integration/views/account/test_account.py, tests/integration/views/account/test_password_change.py
This PR covers two trello cards. 
- changes made to force minimum 12 characters for password.
- changes made to enforce logout when password is changed.
- test min. character for password in account creation, password change, share surveys and transfer surveys
-  test when password is changed you are logged out.
https://trello.com/c/kJqhpjMb/1408-frontstage-password-change-should-invalidate-the-current-session-and-force-logout
https://trello.com/c/V85Hppyn/1409-weak-password-policy
=> Pen Test Force logout on password change and 12 char min for password

_infra/helm/frontstage/Chart.yaml, frontstage/common/authorisation.py, frontstage/error_handlers.py, frontstage/views/sign_in/sign_in.py, tests/integration/test_sign_in.py
Currently, if you access a page you need to be logged in for, it'll redirect you and  put where you came from in the `next` parameter in the http request.  This is bad practice so we needed to change it.  
I took a leaf out of flask-login's book using their `USE_SESSION_FOR_NEXT` functionality to write the next parameter into the flask session (which is an encrypted value saved as a cookie).  The exact bit can be found https://github.com/maxcountryman/flask-login/blob/9c43d645672141aba66e652d0d9484784b429072/flask_login/login_manager.py#L168
A bad actor can't easily modify the flask session cookie and we can write the value to the cookie for the short time needed.
- While logged out, try to access a page that needs authentication, `<host>/my-account` is a good one.
- Check you get …
=> Removing next parameter from url

_infra/helm/frontstage/Chart.yaml, frontstage/views/sign_in/sign_in.py
During the pen test, the `authorization` cookie generated when a user logs in was discovered to not have the `samesite` setting set. This PR sets the cookie to `strict` (which is also used for the `authorization` cookie in response ops).
Log in to front stage with Google Chrome, click on the three dots in the top-right corner of your window, click on "more tools", then "developer tools", then in the developer tools menu, click "application" in the top bar, followed by "cookies" in the left menu. Ensure that the `authorization` cookie's `samesite` variable is set to `strict`.
[Card](https://trello.com/c/lrVwM0jo)
=> setting samesite cookie to strict

_infra/helm/frontstage/Chart.yaml, frontstage/templates/cookies.html
This PR updates the cookies preference page, making sure cookie preference are saved correctly to ons_cookie_policy. The component was missing a required parameter class (ons-js-return-link) which creates a return to link. The onsPanel class also needed updating to ons-cookies-confirmation-message so visibility could be toggled on after the update. I also matched the DS style and update the title to H2
N.B attempts to add a test for this were unsuccessful, this was down to how ons_cookie_policy policy is created and trying to then get hold of it and change it in integration tests
Deploy the app locally or push up to GCP. Note your current cookie settings, you should have a cookie called ons_cookie_policy, (for chrome and local chrome://settings/cookies/detail?site=localhost&search=chrome) …
=> Fix cookies preference page

.github/workflows/comment.yml, .github/workflows/main.yml, _infra/helm/frontstage/Chart.yaml
This PR updates Github actions to fix "service_account_key" has been deprecate. Replacing it with google-github-actions/auth in both main.yml and comment.yml
For main.yml check https://github.com/ONSdigital/ras-frontstage/runs/7210847187?check_suite_focus=true
For comment.yml see https://github.com/ONSdigital/response-operations-ui/pull/747 on how I tested in response-operations, as it is a virtual copy bar the service I didn't repeat it here
=> Fix security account key deprecation

_infra/helm/frontstage/Chart.yaml, _infra/helm/frontstage/templates/frontendconfig.yaml, _infra/helm/frontstage/templates/ingress.yaml, _infra/helm/frontstage/values.yaml
Upon attempting to deploy a previous [a previous PR](https://github.com/ONSdigital/ras-frontstage/pull/846) to preprod, it failed on account of the `sslPolicy` variable not being understood. Looking up kubernetes documentation, I discovered that ingress resources don't accept `sslPolicy` as a valid parameter. Instead, it has to be in a `FrontendConfig` resource, which I have created a file of for frontstage. The config is based off the example on [this page](https://cloud.google.com/kubernetes-engine/docs/how-to/ingress-features#configuring_ingress_features_through_frontendconfig_parameters).
TBD
[Card](https://trello.com/c/dUS1ubPX)
=> added FrontstageConfig resource

Makefile, README.md, _infra/helm/frontstage/Chart.yaml
A while ago, we split the commands up, mostly so you can run unit tests as they don't have any dependencies and are much faster than the integration tests.
This kindof works, but in practice you almost always run both suites at once anyway and doing this way messes up the coverage report
=> Combine unit and integration test commands

_infra/helm/frontstage/Chart.yaml, _infra/helm/frontstage/templates/frontendconfig.yaml, _infra/helm/frontstage/values.yaml
My second attempt at trying to implement the SSL policy in frontstage was a bust, and I don't immediately know what the issue is. This PR undoes my previous 2 PRs so that frontstage can build and deploy in preprod. This way, no other frontstage cards/PRs will be blocked for the time being.
N/A
[Card](https://trello.com/c/dUS1ubPX)
=> remove ssl config

_infra/helm/frontstage/Chart.yaml, frontstage/controllers/auth_controller.py, frontstage/controllers/case_controller.py, frontstage/controllers/notify_controller.py, frontstage/controllers/party_controller.py, frontstage/templates/register/register.enter-your-details.html, frontstage/views/register/enter_account_details.py, frontstage/views/sign_in/sign_in.py, tests/integration/test_registration.py
The errors around account creation failures weren't easy to diagnose, so this PR adds a little more logging and more accurate status codes to help figure out future issues.
- Deploy this and the party PR with the same branch name (https://github.com/ONSdigital/ras-party/pull/371) to your environment. 
- Run the acceptance tests to seed data
- Try to create an account that already exists ([example@example.com](mailto:example@example.com)) and look at both the frontstage and party logs. The logging should make it more clear what is going on.
- Try and create an account to make sure nothing else has broken!
=> Improve error handling around account creation

_infra/helm/frontstage/Chart.yaml, _infra/helm/frontstage/templates/frontendconfig.yaml, _infra/helm/frontstage/values.yaml
Upon doing further research into this SSL policy problem, I realised that the issue wasn't with my config for frontstage, but with the spinnaker service account permissions. As such, I have re-added the frontendconfig resource from my previous PR with the same config.
[Card](https://trello.com/c/dUS1ubPX)
=> re-added frontendconfig

_infra/helm/frontstage/Chart.yaml, frontstage/views/passwords/reset_password.py, tests/integration/test_passwords.py
When a password verification token was out of date, it is deleted from the DB but the password reset counter is not reset to 0 (it will always be greater than 0). When the user tries to reset their password, the code evaluates an 'if' statement that checks if the reset count is greater than 0 (which it will be) it will then execute the try block within that searches for the deleted token within a dictionary. As it is has been deleted, it is not in the dictionary and so an error is thrown. 
To fix the issue, I have added an additional check to see if token is included as part of the dictionary. If it is not, then a new token will be generated (the reset count will not be affected). The user will then be able to receive the password reset email or will receive the 'tried too many times' …
=> Expired email tokens will cause 500 on password reminder

_infra/helm/frontstage/Chart.yaml, _infra/helm/frontstage/templates/frontendconfig.yaml, _infra/helm/frontstage/templates/ingress.yaml, _infra/helm/frontstage/values.yaml
When I originally attempted to deploy the frontendconfig resource, the ingress didn't pick up the new ssl policy, and I had to set it automatically. This PR should fix this by making it automatic.
Before I merge this in, I'll manually set the ssl policy in preprod back to 1.0, and then, upon merging, it should pick up the new 1.2 policy automatically, without me having to set it manually.
[Card](https://trello.com/c/dUS1ubPX)
=> set ingress resource to use frontendconfig resource

_infra/helm/frontstage/Chart.yaml, frontstage/views/surveys/help/surveys_help.py
This pr reroutes any message that is sent through the path 'Get help with this survey -> something else -> something else' from the general `Technical` inbox to survey specific inboxes.
- Run the acceptance tests
- Send a message using this path
- The message should appear in the `Technical` inbox
- Deploy pr into your environment
- Send another message using this path
- The message should appear in the survey's inbox
https://trello.com/c/60uegL1J/1998-rops-secure-messaging-reroute-something-else-to-survey-teams
=> Reroute 'something else' message to survey teams

Pipfile.lock, _infra/helm/frontstage/Chart.yaml
Updating pipenv due to most recent sdc-cryptography version
Can EQ mock be successfully launched in dev
=> Updating Pipfile.lock

.github/workflows/main.yml, _infra/helm/frontstage/Chart.yaml
Currently on a push to a PR each repo builds to latest in onsrasrm-management, however this is the default artifact for all builds when using spinnaker. This means if any change to the charts are made and a PR is created it can and will break dev for everyone. 
Check the build (Publish dev Chart) and make sure it is writing naming the artifact correctly, it should be xx-pr-xx.tgz. You can also check on GCP in ons-rasrmbs-management that the artifact was written out at the right time
=> Update Publish dev Chart

Makefile, Pipfile.lock
Currently we have 2 pipenv checks that are failing the build, one concerns py and the other one is a temporary fix which ignores 51499: wheel
Test everything still works
=> Remove pipenv check

Makefile, Pipfile.lock, _infra/helm/frontstage/Chart.yaml
pipenv check -i 51499 was introduced to temporarily remove the check on Wheel, now that it has been fixed, this PR updates the packages and removes the ignore
Make sure everything works
=> Remove pipenv ignore checks

Pipfile.lock, _infra/helm/frontstage/Chart.yaml, frontstage/common/eq_payload.py, frontstage/controllers/case_controller.py, frontstage/views/surveys/access_survey.py, tests/integration/test_generate_eq.py, tests/integration/test_passwords.py, tests/integration/views/surveys/test_access_survey.py, tests/unit/controllers/test_case_controllers.py, tests/unit/controllers/test_collection_exercise_controller.py
Now that no exercises are using EQ v2 anymore, we can start removing all mentions of the old platform.  This PR ignores the version of EQ that the collection exercise states (which should be v3 anyway, but it's in theory still possible for v2 ones to be made) and just creates a v3 payload and goes to v3 regardless.
- Create exercise (manually or via acceptance tests)
- Set exercise to v2 (via UI or database)
- Have it go live and enrol for it
- Launch it, it should take you to the v3 endpoint in mock-eq.  You can also double check here that the eqVersion for the exercise is v2 to make sure.
=> Remove eq version code

Pipfile, Pipfile.lock, _infra/helm/frontstage/Chart.yaml, config.py, frontstage/__init__.py, frontstage/i18n/translations.py, frontstage/views/cookies.py, frontstage/views/privacy.py, tests/integration/test_message_helper.py, tests/unit/controllers/test_case_controllers.py
The unit tests in frontstage were only able to be run with an instance of redis also running, otherwise multiple tests would fail. This Pr addresses that by introducing a redis mock (fakeredis) to be used in testing. 
Run frontstage unit tests with and without a running instance of redis, all tests should pass both times. 
https://jira.ons.gov.uk/secure/RapidBoard.jspa?rapidView=1493&projectKey=RAS&view=detail&selectedIssue=RAS-639
=> Mock redis in frontstage tests

_infra/helm/frontstage/Chart.yaml, _infra/helm/frontstage/templates/hpa.yaml
Update autoscaling from v2beta2 to v2
The HPA change has already been proven here https://github.com/ONSdigital/ras-party/pull/389, but can be done again if required, just deploy via helm
=> Update HPA to v2

.github/PULL_REQUEST_TEMPLATE.md, _infra/helm/frontstage/Chart.yaml, frontstage/common/session.py, frontstage/templates/layouts/_base.html, frontstage/views/account/account.py, frontstage/views/account/account_survey_share.py, frontstage/views/account/account_transfer_survey.py, frontstage/views/secure_messaging/create_message.py, frontstage/views/secure_messaging/message_get.py, frontstage/views/session.py, frontstage/views/surveys/add_survey.py, frontstage/views/surveys/add_survey_confirm_organisation_survey.py, frontstage/views/surveys/add_survey_submit.py, frontstage/views/surveys/help/surveys_help.py, frontstage/views/surveys/help/technical_help.py, frontstage/views/surveys/surveys_list.py, frontstage/views/surveys/upload_survey.py, frontstage/views/surveys/upload_survey_failed.py, tests/integration/views/test_session.py
There is a requirement that people logged into frontstage need to be notified that they will be logged out 60 seconds before their session times out. They can either stay on the page and their timeout counter will be refreshed or they will be redirected to the login screen.
These code changes will achieve this.
1. Sign into frontstage with a user account
2. Once redirected to the todo survey list keep the page loaded and do not navigate anywhere whilst logged in with the above user account
3. After 59 minutes have elapsed, a message will appear on the screen with a counter
4. Test both the following:
- Click the 'Continue survey' button and you should be on the same screen that you you originally opened
-  Click the 'Continue survey' button once the timer has counted down. This will …
=> RAS-739: Add modal to base template

_infra/helm/frontstage/Chart.yaml, frontstage/common/eq_payload.py, tests/integration/test_generate_eq.py
This PR updates the payload sent to eQ to v2. It also adds much needed payload tests, which were lacking and should really have been there before
The best way is to expose the payload and then validate it against https://github.com/ONSdigital/ons-schema-definitions#json-schema-validation. 
N.B There is some strange config differences when using response_expires with different timezones being used. I will raise another card for this, but considering we didn't test anything before, this is a large step in the right direction
=> RAS-765 Update eq payload to V2

_infra/helm/frontstage/Chart.yaml, frontstage/templates/layouts/_base.html
It looks like there might be a race condition (it could be something else, I haven't fully debugged) with the modal timeout and the authorization cookie, the modal is calling to the expire-at when created and finding there isn't a cookie sometimes and raising a 401. This is not a fix, purely a removal at present, another PR will follow this
Just make sure you can login and navigate around and the modal code has gone from the html
=> Remove timeout modal

_infra/helm/frontstage/Chart.yaml, frontstage/controllers/party_controller.py, tests/unit/controllers/test_party_controller.py
The filter to get live not ended collection exercises needed to removed from frontstage because we already have the ability to get those from the collection exercise service. Additionally, tests that tested this functionality have been removed since they're no longer necessary.
Deploy, run acceptance tests, and make sure they pass.
[Card](https://jira.ons.gov.uk/browse/RAS-791)
=> Ras 791 removing filter

_infra/helm/frontstage/Chart.yaml, frontstage/static/css/theme.css, frontstage/templates/help/help-info-something-else.html, frontstage/templates/help/help-who-is-ons.html, frontstage/templates/surveys/help/surveys-help-exemption-completing-survey.html, frontstage/templates/surveys/help/surveys-help-how-long-selected-for.html, frontstage/templates/surveys/help/surveys-help-info-something-else.html, frontstage/templates/surveys/help/surveys-help-time-to-complete.html, frontstage/templates/surveys/help/surveys-help-who-is-the-ons.html, frontstage/templates/surveys/help/surveys-help-why-selected.html
I missed something in the last design system upgrade where the icons that appear near links (such as on the About the ONS info page) appeared enormous. This turned out to be because the design system v65 renamed the `ons-svg-icon` to `ons-icon` (this wasn't mentioned in the breaking changes!).
Also, the design system upgrade messed with the appearance of the tab component due to the fact that the way we use it is not in accordance with the design system's ethos. The way the tabs are currently created is by a hacky HYML code block, which isn't how it's meant to be done, but it allows us to have the appropriate functionality. To continue supporting our implementation of tabs, the .css file has had some additional config in order to maintain its current appearance. Also, make sure that the …
=> fix ons-icon in html files

_infra/helm/frontstage/Chart.yaml, frontstage/views/surveys/add_survey.py
A user us reporting that the IAC they have been supplied with is not working. At the same time the user does this, we have noticed an error in the logs indicating that an IAC does not pass verification. Unfortunately, the IAC itself is not captured. This PR adds the IAC to the error message.
1. Find an active IAC
2. Login to Frontstage and click 'add a new survey to your account](http://localhost:8082/surveys/add-survey'
3. Enter the IAC into the input field but add an additional character or whitespace
4. Click continue
5. An error message should appear on screen
6. Goto the logs and search for the IAC (with the additional character(s)/whitespace)
7. The message should read '{"enrolment_code": "[YOUR_IAC] ", "event": "Invalid character length, must be 12 characters", "severity": "info", …
=> RAS-888:RITM1072728 - Enrolment Code not Working

_infra/helm/frontstage/Chart.yaml, frontstage/error_handlers.py
At present when a user tries to share/transfer a survey to an existing user it will raise a 401 on the email link click if the user is not logged in, which will be the majority of time and redirect them to the sign-in page. At present if the user then  logs in it takes them to the TODO page missing out the code needed to execute the share/transfer
We shouldn't be raising a 401 in this situation, however that is being fixed in a different card. This is purely an ugly fix that allows the previous url to be passed back in when the user does log in
N.B I am not going to write tests for this one as it really shouldn't behaviour like this. There is a card in tech to discuss it properly, but quick and dirty fix was the decision in stand-up
Start off by getting an environment up and running and …
=> RAS-893 shared survey not appearing in their account

_infra/helm/frontstage/Chart.yaml, frontstage/templates/layouts/_base.html
Due to the potential security risk, we should not currently include the gtm.html snippet in the page to avoid sending any GTM managed metrics to Google Tag Manager in prod and preprod.
This will need to be tested within preprod. 
After the deployment I will use Tag Assistant 
Tag Assistant lets you quickly see which of your site's trackers are working as expected. And if there are issues.
I expect tag assistant to inform me that it was unable to find any data due to the snippet not being present.
https://jira.ons.gov.uk/browse/RAS-905
=> update code to render GTM and GA snippet based on if its present in config

Pipfile.lock, _infra/helm/frontstage/Chart.yaml
Pipfile.lock d31989 was missing from the merge to main for release 2.4.85.
While this didn't stop that release being built, it did mean PRs opened from main after that merge are broken as the pipenv doesn't detect the Pipfile needs re-generating.
Ensure the GHA build passes and also doesn't need to re-create the Pipfile.lock while installing the virtualenv.
As per this PR's GHA build https://github.com/ONSdigital/ras-frontstage/actions/runs/6850260177/job/18624077379#step:5:74
=> Adding Pipfile.lock d31989

_infra/helm/frontstage/Chart.yaml, _infra/helm/frontstage/templates/deployment.yaml, _infra/helm/frontstage/values.yaml, config.py, frontstage/__init__.py
Talisman by default has session cookie secure to True https://github.com/GoogleCloudPlatform/flask-talisman/blob/master/flask_talisman/talisman.py#L78, however we need to be able to control this for the performance environment and dev where it shouldn't be on. This will allow non https sites to still access the cookie which holds the value for csrf. Normal issues with our set-up and that the yaml will not build out till merge
Run the app with data and make sure you can log in
=> Add Talisman session cookie secure

.github/workflows/main.yml, Pipfile, Pipfile.lock, _infra/helm/frontstage/Chart.yaml
Upgrading flask to version 3.0.0, the only changes that seem to affect frontstage are to the markup import which is used to display the success boxes when a message is successfully sent (and other things)
Deploy to your environment and run the acceptance tests, send a message from frontstage and check that the confirmation message is correctly flashed
https://jira.ons.gov.uk/browse/RAS-938
=> RAS-938 Upgrade Frontstage to Flask 3

.github/workflows/comment.yml, .github/workflows/main.yml, _infra/helm/frontstage/Chart.yaml
This PR replaces set-output within the .github workflow file with environment variables to fix a deprecation with set-output. It also updates actions/auth to v2.
Check the github builds for any deprecation warnings and ensure the workflow functions after the changes.
https://jira.ons.gov.uk/secure/RapidBoard.jspa?rapidView=1493&projectKey=RAS&view=detail&selectedIssue=RAS-915
=> Replace set-output with environment variables

_infra/helm/frontstage/Chart.yaml, frontstage/controllers/conversation_controller.py, frontstage/views/secure_messaging/message_get.py, frontstage/views/surveys/help/surveys_help.py, frontstage/views/surveys/help/technical_help.py, tests/integration/controllers/test_conversation_controller.py, tests/integration/test_message_get.py
The changes in SM recently introduced a bug when answering a thread, the msg_to was not being passed and therefore was always going back to group, this leads to 2 errors
"When an internal user sends a secure message on ABS and the respondent returns a message, this is going to the ABS team and not in the 'my messages' tab of the person who is dealing with the message. "
"Incoming SDCs are showing as Initials and missing the previous message thread, appears to be affecting all survey inboxes"
This PR adds in the msg_to and corrects some other minor issues spotted when going over it. It also restores get_msg_to and the tests that went with it
Create a new collection exercise and make it live (or use acceptance tests) now in ROPs create a user and send a message to an enrolled respondent. Go …
=> RAS-1150 Secure messages going to team mailbox instead of to user on ABS

_infra/helm/frontstage/Chart.yaml, frontstage/templates/account/account-something-else.html, frontstage/templates/secure-messages/conversation-view.html, frontstage/templates/secure-messages/help/secure-message-send-messages-view.html, frontstage/templates/secure-messages/help/secure-message-send-technical-messages-view.html
When a message is sent and there is a delay, the submit button remains active. The submit can then be clicked 'X' amount of times leading to an equivalent 'X' amount of duplicates. The 'loader' variant has been added to the submit button. The submit button will no longer be active, a loading wheel will appear on the button and will prevent the button being clicked.
- Run acceptance tests
- Pull this PR
- Add 'time.sleep(30)' to
https://github.com/ONSdigital/ras-frontstage/blob/452e73333c025e0176502c7ea059fe45c1b8bfbf/frontstage/controllers/conversation_controller.py#L135
to cause a delay
- Run this PR locally
- Send a message in frontstage (both technical and non-technical)
- The submit button should look like this
-After the delay, you should be redirected to the inbox overview page …
=> RAS-1101: Bug in secure messaging pre prod - Message sends twice

_infra/helm/frontstage/Chart.yaml, frontstage/controllers/party_controller.py, tests/integration/views/surveys/help/test_surveys_help_something_else.py, tests/integration/views/surveys/help/test_technical_help_survey_not_listed.py
get_business_by_ru_ref is not used in frontstage, but is calling an endpoint which is used by rops that need rationalising. There are also unnecessary mocks which can be remove
Make sure the function is not used
=> RAS-1181 Remove get_business-by-ru-ref from frontstage

Makefile, Pipfile.lock, README.md, _infra/helm/frontstage/Chart.yaml
pytest-html offers a nice way to show test reports when devving locally. This exposes it through a make command
`make test-html`
=> Add test-html to Makefile

Makefile, _infra/helm/frontstage/Chart.yaml, frontstage/common/eq_payload.py, tests/integration/test_generate_eq.py, tests/test_data/collection_exercise/collection_exercise.json, tests/test_data/collection_exercise/collection_exercise_v3.json, tests/test_data/collection_exercise/collection_exercise_with_supplementary_dataset.json
EQ v2 has been dead for some time, this removes the concept of a particular version. It also temporarily mutes the Jinja vulnerability as the fix hasn't yet been released
General smoke test around surveys
RAS-1144
=> Remove EQ version

.github/workflows/main.yml, Pipfile.lock, _infra/helm/frontstage/Chart.yaml
Updates the version of sdc-cryptography to address a vulnerability.
Check all works after the version bump.
https://jira.ons.gov.uk/secure/RapidBoard.jspa?rapidView=1493&projectKey=RAS&view=detail&selectedIssue=RAS-1237
=> Update sdc-cryptography 2.1.1

.github/workflows/main.yml, README.md, frontstage/templates/contact-us.html, tests/unit/views/test_cookies_and_contact.py
As part of the updated user help journey we want to improve the contact us page before a user has logged in to enhance user experience. 
Ensure the implementation matches the Figma documents and the contact us page is working correctly. 
N.B. There is an upcoming card to update the contact us after login, which will contain the functionality to separate the two pages.
https://jira.ons.gov.uk/secure/RapidBoard.jspa?rapidView=1493&projectKey=RAS&view=detail&selectedIssue=RAS-1155
=> Contact us before login

_infra/docker/Dockerfile, _infra/helm/frontstage/Chart.yaml
Reverts ONSdigital/ras-frontstage#996 because of an issue with gnupg causing errors when trying to upload a seft
- deploy to your env 
- make sure frontstage still works
- ensure you can still upload a seft to frontstage
[RAS-1322](https://jira.ons.gov.uk/browse/RAS-1322)
=> Revert "RAS-1305 Introduce non root application user"

_infra/docker/Dockerfile, _infra/helm/frontstage/Chart.yaml
The current Python app is running as `root`. This adds an `appuser` to run the Python app. The previous attempt to do this caused the error
```
gpg: Fatal: can't create directory '/home/appuser/.gnupg': No such file or directory
```
This was due to the `gnupg` library having OS file system dependencies as detailed in the docs https://gnupg.readthedocs.io/en/latest/#before-you-start
The `useradd`  Linux command does not create a `/home` directory for the user being added and has no option to do so. There is an alternative `adduser` command that accepts a flag to create a home directory, however the approach in this PR to manually create the directory is more explicit.
**NOTE:** The continued use of the `/home` directory within the container OS is NOT good practice. However, this is …
=> Add image appuser

.github/workflows/main.yml, Dockerfile, Pipfile, Pipfile.lock, README.md, _infra/docker/Dockerfile, _infra/helm/frontstage/Chart.yaml
Upgrades python to 3.12 as part of ongoing tech upgrades. 
Remove your existing pipenv with 3.11
Install python 3.12 (I used pyenv) either globally or a new local version.
Create a new environment with pipenv install 
Check your python interpreter has updated or add a new one based off the created pipenv if it isn't using 3.12
Run the tests and app locally 
Deploy this PR, run acceptance tests and check frontstage is working correctly. 
https://jira.ons.gov.uk/secure/RapidBoard.jspa?rapidView=1493&projectKey=RAS&view=detail&selectedIssue=RAS-1379
=> Upgrade python version to 3.12

_infra/helm/frontstage/Chart.yaml, frontstage/common/redis_cache.py, frontstage/controllers/case_controller.py, frontstage/controllers/party_controller.py, frontstage/views/surveys/download_survey.py, frontstage/views/surveys/upload_survey.py, tests/unit/controllers/test_party_controller.py, tests/unit/test_redis_cache.py
This PR updates the survey_list build process, instead of using redis and calling to party/survey multiple times it is provided on the first call. It also adds a call to a new endpoint specially for checking a respondent is enrolled 
Deploy this card as well https://github.com/ONSdigital/ras-party/pull/449. Add some enrolment data to your account, acceptance tests could be used, but you might want to add another IAC as well. If it logs in you are good. Also check you can access a eq, download and upload a seft
=> RAS-1400 Extend party enrolment to include business and survey details

_infra/helm/frontstage/Chart.yaml, frontstage/controllers/conversation_controller.py
It was was found during the testing of https://jira.ons.gov.uk/browse/RAS-1402 that a message could not be sent from Frontstage when the secure message V2 was switched on. This wasn't noticed until preprod as this was unexpected. It was nothing to do with the code change as part of the reference Jira card it was just a more in depth test was conducted which highlighted the defect. 
The problem being was that SM V1 stores empty survey_ids as empty strings whereas SM V2 uses a 'None' value. So this will break SM V2 which is implemented to except optional UUIDs.
This change should fix the issue. 
- Send a new 'Something else' message in Frontstage via the 'My Account' screen
- Go back to the sent message screen and try to send another message in the same thread
- This should send correctly …
=> Fix issue of sending blank surveyID to SMV2

Makefile, frontstage/templates/partials/useful_links.html, frontstage/templates/surveys/surveys-history.html, frontstage/templates/surveys/surveys-todo.html
Introduces the useful links component to the survey home and completed surveys page
Check the component matches the intended design docs and that the navigation is as expected.
**N.B.** 
- The ui is a bit compact as it is not using the updated surveys home and completed pages. 
- The tablist also looks a bit odd as it doesn't use the full grid width but that is being removed on the banner menu heading ticket. 
- The breadcrumbs on the last 2 links don't work and take you to the sign in page and the cancel buttons take you to unexpected pages. We need to revisit breadcrumbs to make them dynamic.
[RAS-1285](https://jira.ons.gov.uk/browse/RAS-1285)
=> Useful links component

frontstage/templates/contact-us.html
This PR updates the breadcrumb navigation on the contact us page, to reflect the new survey help journey. 
Deploy this PR to your environment 
Check when not signed in that the breadcrumbs take you back to the sign in page. 
Check when signed in that the contact us breadcrumbs either from the footer or from the useful links takes you back to the previous page you were on. 
[RAS-1489](https://jira.ons.gov.uk/browse/RAS-1489)
=> Update contact us breadcrumb navigation

_infra/helm/frontstage/Chart.yaml, _infra/helm/frontstage/templates/ingress.yaml
`kubernetes.io/ingress.class: gce` is deprecated as of kubernetes 1.18 in favor of 
```
spec:
ingressClassName: gce
```
This PR introduces the new ingress class annotation to resolve the deprecation warning however the old annotation is persisted due to compatibility with GKE https://cloud.google.com/kubernetes-engine/docs/concepts/ingress#deprecated_annotation
- Deploy your dev environment
- Uninstall/delete your deployment of frontstage through helm. (you will also need to delete the external secrets, backend config).
- helm install frontstage on latest with ingress.enabled="true", you should see a deprecation warning:
`annotation "kubernetes.io/ingress.class" is deprecated, please use 'spec.ingressClassName' instead`
- Pull this PR, delete and reinstall frontstage with ingress enabled …
=> Update deprecated ingress class annotation

_infra/helm/frontstage/Chart.yaml, frontstage/common/eq_payload.py, frontstage/common/redis_cache.py, frontstage/controllers/collection_instrument_controller.py, tests/integration/mocked_services.py, tests/integration/test_generate_eq.py, tests/integration/views/surveys/test_access_survey.py, tests/test_data/registry_instrument/registry_instrument.json, tests/unit/test_redis_cache.py
As part of the ongoing CIR work and integration, Frontstage needs to send the CIR GUID (when present) to EQ. This achieves this.
Run unit and acceptance tests
1. Complete a CE and add a CI with a matching version (you will have to check the DB for one)
2. Set CE as live
3. In Frontstage, register a user to the CE
4. Complete the survey
5. Repeat the above except add a CI that doesn't have a version
6. Both times, mock EQ will be launched
https://officefornationalstatistics.atlassian.net/browse/RAS-1654
=> RAS-1654: CIR - RASRM and EQ launching

_infra/docker/Dockerfile, _infra/helm/frontstage/Chart.yaml
Latest version of python:3.12-slim has caused GPG to fail. Pegging the imaged to python:3.12.10-slim has solved the issue.
=> Fix for SEFT upload

_infra/helm/frontstage/Chart.yaml, frontstage/common/eq_payload.py, tests/integration/test_generate_eq.py
To align with the existing platform [schema documentation for EQ launch](https://github.com/ONSdigital/ons-schema-definitions/blob/main/schemas/launch_v2.json#L74-L83), this PR ensures the payload contains one-of `schema_name` or `cir_instrument_id`
- run the tests
- create a QBS CE with CIR version selected through to go live
- launch an EQ and ensure `schema_name` is NOT present and `cir_instrument_id` is present in the Mock EQ launch claims
- manually delete the registry_instrument from the rasci schema
- clear your redis cache (FLUSHALL in the cli can be used)
- re-launch the EQ and ensure `schema_name` is present and `cir_instrument_id` is NOT present in the Mock EQ launch claims
https://officefornationalstatistics.atlassian.net/browse/RAS-1654
=> Ensure EQ payload contains one-of cir_instrument_id or schema_name
